package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class EdlActivity extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_edl);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());findViewById(R.id.btn_SAHARA_TEST).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara"));
findViewById(R.id.btn_SAHARA_Upload).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"));
findViewById(R.id.btn_PRINT_GPT_UFS).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"));
findViewById(R.id.btn_PRINT_GPT_EMMC).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=emmc --printgpt"));
findViewById(R.id.btn_PARTITION_MANAGER).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"));
findViewById(R.id.btn_FLASH_Flat_Build_rawprogram_patch).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --rawprogram=/sdcard/Download/rawprogram0.xml --patch=/sdcard/Download/patch0.xml --memory=ufs"));
findViewById(R.id.btn_READ_frp_100MB).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=frp --filename=/sdcard/Download/frp.img"));
findViewById(R.id.btn_READ_userdata_1GB).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=userdata --filename=/sdcard/Download/userdata.img"));
findViewById(R.id.btn_ERASE_frp).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"));
findViewById(R.id.btn_ERASE_userdata).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=userdata"));
findViewById(R.id.btn_BACKUP_QCN_modemst1_modemst2_fsg).setOnClickListener(v->run("dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img; dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img; dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img"));
findViewById(R.id.btn_RESTORE_QCN).setOnClickListener(v->run("dd if=/sdcard/Download/modemst1.img of=/dev/block/bootdevice/by-name/modemst1"));
findViewById(R.id.btn_RESET_to_normal).setOnClickListener(v->run("edl reset"));
findViewById(R.id.btn_SELECT_PORT_COM).setOnClickListener(v->run("edl --help"));
}void run(String c){bar.setProgress(5);log.append("\n> "+c+"\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\n"));}}).start();}}