
package com.otgflasher.pro;
import android.app.Activity;import android.os.Bundle;import android.widget.*;import android.view.View;import java.io.*;import java.util.*;import java.util.zip.*;import android.content.*;
public class FileManagerActivity extends Activity {
    TextView txtPath, txtSelected; ListView listFiles; ProgressBar fmProgress;
    File cur=new File("/sdcard/Download"); List<File> files=new ArrayList<>(); File selected=null; String clipboard=""; boolean isCut=false;
    @Override protected void onCreate(Bundle b){ super.onCreate(b); setContentView(R.layout.activity_file_manager);
        txtPath=findViewById(R.id.txtPath); txtSelected=findViewById(R.id.txtSelected); listFiles=findViewById(R.id.listFiles); fmProgress=findViewById(R.id.fmProgress);
        findViewById(R.id.btnBack).setOnClickListener(v->finish());
        findViewById(R.id.btnUp).setOnClickListener(v->{ if(cur.getParentFile()!=null){ cur=cur.getParentFile(); list(); }});
        findViewById(R.id.btnExtract).setOnClickListener(v->extract());
        findViewById(R.id.btnCreateZip).setOnClickListener(v->createZip());
        findViewById(R.id.btnCreateTar).setOnClickListener(v->createTarGz());
        findViewById(R.id.btnCopy).setOnClickListener(v->{ if(selected!=null){ clipboard=selected.getAbsolutePath(); isCut=false; txtSelected.setText("COPIED: "+selected.getName()+" -> buka folder tujuan untuk paste"); }});
        findViewById(R.id.btnCut).setOnClickListener(v->{ if(selected!=null){ clipboard=selected.getAbsolutePath(); isCut=true; txtSelected.setText("CUT: "+selected.getName()); }});
        findViewById(R.id.btnDelete).setOnClickListener(v->{ if(selected==null) return; new android.app.AlertDialog.Builder(this).setTitle("Delete?").setMessage("Delete "+selected.getName()+"?").setPositiveButton("Yes",(d,w)->{ deleteRec(selected); list(); }).setNegativeButton("No",null).show(); });
        findViewById(R.id.btnRename).setOnClickListener(v->{ if(selected==null) return; EditText et=new EditText(this); et.setText(selected.getName()); new android.app.AlertDialog.Builder(this).setTitle("Rename").setView(et).setPositiveButton("OK",(d,w)->{ File nf=new File(selected.getParent(), et.getText().toString()); selected.renameTo(nf); selected=nf; list(); }).setNegativeButton("Cancel",null).show(); });
        findViewById(R.id.btnFlashHere).setOnClickListener(v->{ if(selected==null) return; String p="boot"; String n=selected.getName().toLowerCase(); if(n.contains("recovery")) p="recovery"; else if(n.contains("vbmeta")) p="vbmeta"; else if(n.contains("super")) p="super"; else if(n.contains("system")) p="system"; new android.app.AlertDialog.Builder(this).setTitle("Flash?").setMessage("Flash "+selected.getName()+" as "+p+"?\nfastboot flash "+p+" "+selected.getAbsolutePath()).setPositiveButton("Flash",(d,w)->{ try{ Runtime.getRuntime().exec(new String[]{"sh","-c","fastboot flash "+p+" '"+selected.getAbsolutePath()+"' 2>&1"}); Toast.makeText(this,"Flashing "+p,Toast.LENGTH_LONG).show(); }catch(Exception e){} }).setNegativeButton("Cancel",null).show(); });
        findViewById(R.id.btnProps).setOnClickListener(v->{ if(selected==null) return; String info="Name: "+selected.getName()+"\nPath: "+selected.getAbsolutePath()+"\nSize: "+selected.length()/1024/1024+" MB ("+selected.length()+" bytes)\nDate: "+new java.util.Date(selected.lastModified())+"\nRead: "+selected.canRead()+" Write: "+selected.canWrite()+"\nIsDir: "+selected.isDirectory(); new android.app.AlertDialog.Builder(this).setTitle("Properties").setMessage(info).setPositiveButton("OK",null).show(); });
        listFiles.setOnItemClickListener((a,vw,pos,id)->{ File f=files.get(pos); if(f.isDirectory()){ cur=f; list(); } else { selected=f; txtSelected.setText("SELECTED: "+f.getName()+" | "+f.length()/1024/1024+"MB | "+f.getAbsolutePath()); if(!clipboard.isEmpty()){ paste(); } }});
        listFiles.setOnItemLongClickListener((a,vw,pos,id)->{ File f=files.get(pos); selected=f; showMenu(f); return true; });
        list();
    }
    void list(){ File[] arr=cur.listFiles(); files.clear(); List<String> names=new ArrayList<>(); if(arr!=null){ Arrays.sort(arr,(x,y)->{ if(x.isDirectory()&&!y.isDirectory()) return -1; if(!x.isDirectory()&&y.isDirectory()) return 1; return x.getName().compareToIgnoreCase(y.getName()); }); for(File f:arr){ if(f.getName().startsWith(".")) continue; files.add(f); String icon=f.isDirectory()?"📁 ":"📄 "; if(f.getName().endsWith(".zip")||f.getName().endsWith(".rar")) icon="📦 "; if(f.getName().endsWith(".img")||f.getName().endsWith(".bin")) icon="💾 "; if(f.getName().endsWith(".apk")) icon="📱 "; names.add(icon+f.getName()+"\n "+(f.isDirectory()?"<DIR>":f.length()/1024/1024+" MB")+" | "+new java.text.SimpleDateFormat("dd/MM/yy").format(new java.util.Date(f.lastModified()))); } } txtPath.setText(cur.getAbsolutePath()+" ("+files.size()+" items)"); listFiles.setAdapter(new ArrayAdapter<>(this, android.R.layout.simple_list_item_1, names)); if(!clipboard.isEmpty()) txtSelected.setText("CLIPBOARD: "+new File(clipboard).getName()+" ("+(isCut?"CUT":"COPY")+") - tap folder untuk paste"); }
    void paste(){ if(clipboard.isEmpty()) return; new Thread(()->{ try{ File src=new File(clipboard); File dst=new File(cur, src.getName()); if(src.isFile()){ copyFile(src,dst); if(isCut) src.delete(); } runOnUiThread(()->{ list(); clipboard=""; }); }catch(Exception e){} }).start(); }
    void copyFile(File s, File d)throws Exception{ FileInputStream fis=new FileInputStream(s); FileOutputStream fos=new FileOutputStream(d); byte[] b=new byte[8192]; int l; while((l=fis.read(b))>0) fos.write(b,0,l); fis.close(); fos.close(); }
    void extract(){ if(selected==null){ Toast.makeText(this,"Pilih file zip dulu",Toast.LENGTH_SHORT).show(); return; } fmProgress.setVisibility(View.VISIBLE); new Thread(()->{ try{ String name=selected.getName().toLowerCase(); int count=0; if(name.endsWith(".zip")){ ZipInputStream zis=new ZipInputStream(new FileInputStream(selected)); ZipEntry ze; while((ze=zis.getNextEntry())!=null){ File out=new File(cur, ze.getName()); if(ze.isDirectory()) out.mkdirs(); else { out.getParentFile().mkdirs(); FileOutputStream fos=new FileOutputStream(out); byte[] b=new byte[8192]; int l; while((l=zis.read(b))>0) fos.write(b,0,l); fos.close(); count++; } zis.closeEntry(); } zis.close(); } else if(name.endsWith(".tar.gz")||name.endsWith(".tgz")){ Process p=Runtime.getRuntime().exec(new String[]{"sh","-c","tar -xzf '"+selected.getAbsolutePath()+"' -C '"+cur.getAbsolutePath()+"' 2>&1"}); p.waitFor(); count=1; } else if(name.endsWith(".gz")){ File out=new File(cur, selected.getName().replace(".gz","")); GZIPInputStream gis=new GZIPInputStream(new FileInputStream(selected)); FileOutputStream fos=new FileOutputStream(out); byte[] b=new byte[8192]; int l; while((l=gis.read(b))>0) fos.write(b,0,l); fos.close(); gis.close(); count=1; } int c=count; runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("EXTRACT DONE: "+c+" files"); list(); }); }catch(Exception e){ runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("EXTRACT ERR: "+e.getMessage()); }); }}).start(); }
    void createZip(){ fmProgress.setVisibility(View.VISIBLE); new Thread(()->{ try{ File zipFile=new File(cur.getParent(), cur.getName()+".zip"); if(selected!=null&&selected.isFile()) zipFile=new File(cur, selected.getName()+".zip"); ZipOutputStream zos=new ZipOutputStream(new FileOutputStream(zipFile)); if(selected!=null&&selected.isFile()){ zos.putNextEntry(new ZipEntry(selected.getName())); FileInputStream fis=new FileInputStream(selected); byte[] b=new byte[8192]; int l; while((l=fis.read(b))>0) zos.write(b,0,l); fis.close(); zos.closeEntry(); } else { for(File f:cur.listFiles()){ if(f.isFile()){ zos.putNextEntry(new ZipEntry(f.getName())); FileInputStream fis=new FileInputStream(f); byte[] b=new byte[8192]; int l; while((l=fis.read(b))>0) zos.write(b,0,l); fis.close(); zos.closeEntry(); } } } zos.close(); runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("ZIP DONE: "+zipFile.getName()+" "+zipFile.length()/1024+"KB"); list(); }); }catch(Exception e){ runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("ZIP ERR: "+e.getMessage()); }); }}).start(); }
    void createTarGz(){ if(selected==null) return; fmProgress.setVisibility(View.VISIBLE); new Thread(()->{ try{ File tarGz=new File(selected.getAbsolutePath()+".tar.gz"); Process p=Runtime.getRuntime().exec(new String[]{"sh","-c","cd '"+cur.getAbsolutePath()+"' && tar -czf '"+tarGz.getAbsolutePath()+"' '"+selected.getName()+"' 2>&1"}); p.waitFor(); runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("TAR.GZ DONE: "+tarGz.getName()); list(); }); }catch(Exception e){ runOnUiThread(()->{ fmProgress.setVisibility(View.GONE); txtSelected.setText("ERR: "+e.getMessage()); }); }}).start(); }
    void deleteRec(File f){ if(f.isDirectory()){ File[] cs=f.listFiles(); if(cs!=null) for(File c:cs) deleteRec(c); } f.delete(); }
    void showMenu(File f){ String[] ops={"Extract Here","Compress to ZIP","Compress to TAR.GZ","Copy","Cut","Delete","Rename","Properties","Flash as Boot","MD5"}; new android.app.AlertDialog.Builder(this).setTitle(f.getName()).setItems(ops,(d,w)->{ switch(w){ case 0: extract(); break; case 1: createZip(); break; case 2: createTarGz(); break; case 3: clipboard=f.getAbsolutePath(); isCut=false; break; case 4: clipboard=f.getAbsolutePath(); isCut=true; break; case 5: deleteRec(f); list(); break; case 6: EditText et=new EditText(this); et.setText(f.getName()); new android.app.AlertDialog.Builder(this).setTitle("Rename").setView(et).setPositiveButton("OK",(dd,ww)->{ File nf=new File(f.getParent(), et.getText().toString()); f.renameTo(nf); list(); }).show(); break; case 7: txtSelected.setText("Size: "+f.length()/1024/1024+"MB Path: "+f.getAbsolutePath()); break; } }).show(); }
}
