package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class MtkActivity extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_mtk);txtDetail=findViewById(R.id.txt_detail);log=findViewById(R.id.log_view);bar=findViewById(R.id.progress_bar);findViewById(R.id.btn_back).setOnClickListener(v->finish());findViewById(R.id.btn_bypass_auth_0).setOnClickListener(v->run("python3 -m mtk payload"));
findViewById(R.id.btn_download_only_1).setOnClickListener(v->run("python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt"));
findViewById(R.id.btn_firmware_upgrade_2).setOnClickListener(v->run("python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --firmware-upgrade"));
findViewById(R.id.btn_format_all_download_3).setOnClickListener(v->run("python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --format-all"));
findViewById(R.id.btn_readback_boot_4).setOnClickListener(v->run("python3 -m mtk r boot /sdcard/Download/boot.img"));
findViewById(R.id.btn_readback_preloader_5).setOnClickListener(v->run("python3 -m mtk r preloader /sdcard/Download/preloader.bin"));
findViewById(R.id.btn_format_auto_6).setOnClickListener(v->run("python3 -m mtk e frp,userdata,cache"));
findViewById(R.id.btn_erase_frp_7).setOnClickListener(v->run("python3 -m mtk e frp"));
findViewById(R.id.btn_erase_frp_userdata_8).setOnClickListener(v->run("python3 -m mtk e frp,userdata"));
findViewById(R.id.btn_memory_test_9).setOnClickListener(v->run("python3 -m mtk da test"));
findViewById(R.id.btn_seccfg_unlock_10).setOnClickListener(v->run("python3 -m mtk da seccfg unlock"));
}void run(String c){bar.setProgress(5);log.append("\n> "+c+"\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\n"));}}).start();}}