package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class SaharaActivity extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_sahara);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());findViewById(R.id.btn_SAHARA_TEST_chip_id).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara --print-chip-id"));
findViewById(R.id.btn_SAHARA_Upload_loader).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"));
findViewById(R.id.btn_DIAG_enable).setOnClickListener(v->run("adb shell setprop sys.usb.config diag,adb"));
findViewById(R.id.btn_DIAG_disable).setOnClickListener(v->run("adb shell setprop sys.usb.config mtp,adb"));
findViewById(R.id.btn_ROOT_magisk_patch_boot).setOnClickListener(v->run("python3 /sdcard/Download/magisk_patch.py /sdcard/Download/boot.img"));
findViewById(R.id.btn_FLASH_magisk_patched_boot).setOnClickListener(v->run("fastboot flash boot /sdcard/Download/magisk_patched.img"));
findViewById(R.id.btn_FLASH_TWRP_recovery).setOnClickListener(v->run("fastboot flash recovery /sdcard/Download/twrp.img"));
findViewById(R.id.btn_DUMP_preloader_via_brom).setOnClickListener(v->run("python3 -m mtk r preloader /sdcard/Download/preloader_dump.bin"));
findViewById(R.id.btn_BROM_bypass_auth).setOnClickListener(v->run("python3 -m mtk payload"));
findViewById(R.id.btn_READ_chip_info_HWID_OEM_PK_hash).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara --print-chip-id"));
findViewById(R.id.btn_LIVE_protocol_console).setOnClickListener(v->run("edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt --verbose"));
}void run(String c){bar.setProgress(5);log.append("\n> "+c+"\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\n"));}}).start();}}