package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class SuperActivity extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_super);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());findViewById(R.id.btn_LPDUMP_list_inside_super).setOnClickListener(v->run("lpdump /sdcard/Download/super.img"));
findViewById(R.id.btn_LPUNPACK_all).setOnClickListener(v->run("lpunpack /sdcard/Download/super.img /sdcard/Download/out/"));
findViewById(R.id.btn_EXTRACT_system).setOnClickListener(v->run("cp /sdcard/Download/out/system.img /sdcard/Download/system.img"));
findViewById(R.id.btn_EXTRACT_vendor).setOnClickListener(v->run("cp /sdcard/Download/out/vendor.img /sdcard/Download/vendor.img"));
findViewById(R.id.btn_EXTRACT_product).setOnClickListener(v->run("cp /sdcard/Download/out/product.img /sdcard/Download/product.img"));
findViewById(R.id.btn_EXTRACT_system_ext).setOnClickListener(v->run("cp /sdcard/Download/out/system_ext.img /sdcard/Download/system_ext.img"));
findViewById(R.id.btn_EXTRACT_odm).setOnClickListener(v->run("cp /sdcard/Download/out/odm.img /sdcard/Download/odm.img"));
findViewById(R.id.btn_MOUNT_system).setOnClickListener(v->run("mkdir -p /mnt/system; mount -o loop /sdcard/Download/out/system.img /mnt/system"));
findViewById(R.id.btn_RESIZE_super).setOnClickListener(v->run("lpresize /sdcard/Download/super.img 0"));
findViewById(R.id.btn_LPMAKE_new_super).setOnClickListener(v->run("lpmake --help"));
findViewById(R.id.btn_FLASH_super_fastboot).setOnClickListener(v->run("fastboot flash super /sdcard/Download/super.img"));
}void run(String c){bar.setProgress(5);log.append("\n> "+c+"\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\n"));}}).start();}}