import os
os.makedirs("app/src/main/java/com/otgflasher/pro",exist_ok=True)
os.makedirs("app/src/main/res/layout",exist_ok=True)
os.makedirs("app/src/main/res/values",exist_ok=True)
open("app/build.gradle","w").write("plugins{ id 'com.android.application' }\nandroid{ compileSdk 34; namespace 'com.otgflasher.pro'; defaultConfig{ applicationId 'com.otgflasher.pro'; minSdk 26; targetSdk 34; versionCode 20; versionName '20.0 FULL TOOLS' } }\ndependencies{ implementation 'androidx.appcompat:appcompat:1.6.1' }\n")
open("app/src/main/res/values/strings.xml","w").write('<resources><string name="app_name">OTG Flasher v9</string></resources>')
open("app/src/main/res/values/themes.xml","w").write('<resources><style name="Theme.OTGFlasher" parent="android:Theme.Material.Light.NoActionBar"/></resources>')
open("app/src/main/AndroidManifest.xml","w").write('<manifest xmlns:android="http://schemas.android.com/apk/res/android"><uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/><uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/><application android:theme="@style/Theme.OTGFlasher" android:label="OTG Flasher v9" android:requestLegacyExternalStorage="true"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><activity android:name=".MtkActivity"/><activity android:name=".FastbootActivity"/><activity android:name=".EdlActivity"/><activity android:name=".OdinActivity"/><activity android:name=".SpdActivity"/><activity android:name=".PayloadActivity"/><activity android:name=".SuperActivity"/><activity android:name=".OfpActivity"/><activity android:name=".FrpActivity"/><activity android:name=".MiActivity"/><activity android:name=".QcnActivity"/><activity android:name=".KgActivity"/><activity android:name=".UnlockActivity"/><activity android:name=".PartActivity"/></application></manifest>')

# MAIN 2 KOLOM GEDE
main='''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#FFFFFF">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="12dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="68dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="16dp"><TextView android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:text="OTG FLASHER v9 - FULL TOOLS" android:textSize="18sp" android:textStyle="bold" android:textColor="#FFFFFF"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp"><LinearLayout android:id="@+id/cFastboot" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="FASTBOOT" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMtk" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="MTK SP" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cEdl" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="EDL 9008" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOdin" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="ODIN" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cSpd" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="SPD PAC" android:textSize="15sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPayload" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="PAYLOAD" android:textSize="15sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cSuper" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="SUPER" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOfp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="OFP" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cFrp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="FRP" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMi" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="MI ACC" android:textSize="15sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cQcn" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="QCN" android:textSize="16sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cKg" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="KG MDM" android:textSize="14sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cUnlock" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp"><TextView android:text="UNLOCK BL" android:textSize="14sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPart" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="130dp" android:background="#FFFFFF" android:gravity="center" android:elevation="4dp" android:layout_marginStart="8dp"><TextView android:text="PARTITION" android:textSize="14sp" android:textStyle="bold" android:textColor="#000000" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
</LinearLayout></ScrollView>'''
open("app/src/main/res/layout/activity_main.xml","w").write(main)

# FULL TOOLS LAYOUTS
def make_full(name, title, fields, buttons):
    field_xml=""
    for f in fields:
        field_xml+=f'<TextView android:text="{f}" android:textSize="11sp" android:textColor="#000000" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp" android:textStyle="bold"/>\n'
        field_xml+=f'<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="48dp" android:background="#EEEEEE" android:gravity="center_vertical" android:padding="8dp"><TextView android:id="@+id/txt_{f.replace(" ","_")}" android:text="/sdcard/Download/" android:textSize="11sp" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"/><Button android:id="@+id/btn_{f.replace(" ","_")}" android:text="BROWSE" android:layout_width="80dp" android:layout_height="38dp" android:textSize="10sp"/></LinearLayout>\n'
    btn_xml=""
    for b in buttons:
        safe=b.replace(" ","_").replace("/","_")
        btn_xml+=f'<Button android:id="@+id/btn_{safe}" android:text="{b}" android:layout_width="match_parent" android:layout_height="60dp" android:textSize="11sp" android:layout_marginTop="6dp" android:backgroundTint="#2ECC71"/>\n'
    xml=f'''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#FFFFFF">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="60dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="10dp"><Button android:id="@+id/btnBack" android:text="BACK" android:layout_width="70dp" android:layout_height="44dp"/><TextView android:text="{title} - FULL TOOLS" android:textSize="14sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:gravity="center"/></LinearLayout>
{field_xml}
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="12dp">
{btn_xml}
</LinearLayout>
<ProgressBar android:id="@+id/progressBar" style="?android:attr/progressBarStyleHorizontal" android:layout_width="match_parent" android:layout_height="18dp" android:max="100" android:layout_marginTop="12dp"/>
<TextView android:id="@+id/txtDetail" android:text="Ready - Full Tools" android:textSize="11sp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"/>
<TextView android:id="@+id/logView" android:text="LOG {title} - FULL" android:textSize="10sp" android:background="#111111" android:textColor="#00FF00" android:padding="8dp" android:layout_width="match_parent" android:layout_height="300dp" android:layout_marginTop="8dp"/>
</LinearLayout></ScrollView>'''
    open(f"app/src/main/res/layout/activity_{name}.xml","w").write(xml)

make_full("fastboot","FASTBOOT",["Partisi boot_a boot_b boot recovery vbmeta_a vbmeta_b super system vendor dtbo modem","File boot.img","File super.img"], ["FLASH boot_a","FLASH boot_b","FLASH boot","FLASH recovery","FLASH vbmeta","FLASH vbmeta_a","FLASH super","FLASH system","ERASE frp","ERASE userdata","SET ACTIVE A","SET ACTIVE B","REBOOT bootloader","REBOOT system","UNLOCK BL","LOCK BL","OEM device-info"])
make_full("mtk","MTK SP FLASH",["Scatter MT6765_scatter.txt","Firmware folder","Auth file auth_sv5.auth","DA file MTK_AllInOne_DA.bin","Preloader preloader.bin"], ["BYPASS AUTH SLA DAA","FLASH Download Only","FLASH Firmware Upgrade","FLASH Format All + Download","READBACK boot 0x0 0x2000000","READBACK preloader","FORMAT frp + userdata","FORMAT all","ERASE FRP","DUMP preloader","REBOOT"])
make_full("edl","EDL 9008",["Loader prog_firehose_ddr.elf","Rawprogram rawprogram0.xml","Patch patch0.xml","Storage UFS or EMMC"], ["SAHARA TEST","PRINT GPT UFS","PRINT GPT EMMC","FLASH QFIL rawprogram+patch","READ frp 100MB","ERASE frp","ERASE userdata","BACKUP QCN modemst1 modemst2 fsg","RESTORE QCN","RESET EDL to normal","READ full dump"])
make_full("odin","SAMSUNG ODIN",["AP file AP_G998.tar.md5","BL file BL_G998.tar.md5","CP file CP_G998.tar.md5","CSC file CSC_OMC.tar.md5","PIT file"], ["FLASH AP only","FLASH BL only","FLASH CP only","FLASH CSC only","FLASH AP+BL+CP+CSC FULL","READ PIT","WRITE PIT","BYPASS KG knoxguard","BYPASS MDM","FRP BYPASS adb","REBOOT download","REBOOT system"])
make_full("spd","SPD PAC",["PAC file firmware.pac","Loader fdl1 fdl2"], ["FLASH PAC full","FLASH PAC format all","READ INFO","READ FLASH","FORMAT","BYPASS FRP","DIAG"])
make_full("payload","PAYLOAD BIN",["payload.bin from OTA","Output folder /sdcard/Download/out/"], ["LIST partitions in payload","EXTRACT ALL","EXTRACT boot","EXTRACT system","EXTRACT vendor","EXTRACT super","EXTRACT dtbo","EXTRACT vbmeta"])
make_full("super","SUPER UNPACK",["super.img","Output folder /sdcard/Download/out/"], ["LIST inside super lpdump","UNPACK ALL lpunpack","EXTRACT system.img","EXTRACT vendor.img","EXTRACT product.img","MOUNT system","RESIZE super","FLASH super"])
make_full("ofp","OFP EXTRACT",["firmware.ofp OPPO Realme","Output folder"], ["EXTRACT OFP all","EXTRACT OFP super only","DECRYPT OFP","LIST OFP","FLASH OFP"])
make_full("frp","FRP BYPASS",["No file needed - device connected"], ["ADB FRP settings secure user_setup_complete 1","ADB FRP remove accounts.db","ADB FRP pm clear gsf login","FASTBOOT ERASE frp","FASTBOOT ERASE config","FASTBOOT ERASE persist","MTK ERASE frp + nvram","EDL ERASE frp","SAMSUNG FRP via adb + cp","UNIVERSAL FRP bypass","RESET FRP"])
make_full("mi","MI ACCOUNT",["No file"], ["DISABLE FindDevice pm disable com.xiaomi.finddevice","ERASE micloud data/system/micloud","DISABLE micloud settings","ERASE frp","ERASE persist","BYPASS Mi Account via adb","REMOVE Mi Account persist.img","REBOOT"])
make_full("qcn","QCN BACKUP",["QCN file backup.qcn","EFS folder"], ["BACKUP QCN dd modemst1","BACKUP QCN dd modemst2","BACKUP QCN dd fsg","BACKUP QCN dd fsc","BACKUP FULL QCN 4 files","RESTORE QCN modemst1","RESTORE QCN modemst2","RESTORE QCN fsg","BACKUP EFS","RESTORE EFS","DIAG enable"])
make_full("kg","KG MDM",["No file"], ["DISABLE KGCLIENT pm disable","DISABLE MDM pm disable","DISABLE KNOX pm disable knox","REMOVE KGCLIENT uninstall","REMOVE MDM","BYPASS KG via adb shell settings","BYPASS KG via build.prop","DISABLE KG via samfw","RESET KG"])
make_full("unlock","UNLOCK BL",["No file"], ["CHECK BL status fastboot oem device-info","UNLOCK flashing unlock","UNLOCK flashing unlock_critical","UNLOCK oem unlock","UNLOCK oem unlock-go","LOCK flashing lock","LOCK flashing lock_critical","MTK UNLOCK","SAMSUNG UNLOCK via oem unlock","RELOCK"])
make_full("part","PARTITION",["No file"], ["PRINT GPT sgdisk --print sda","PRINT GPT gdisk","PRINT partitions parted","BACKUP GPT sda 34 sectors","RESTORE GPT","BACKUP all partitions list","ERASE partition frp","RESIZE super","CREATE partition","DELETE partition","BACKUP super"])

# JAVA MAIN
open("app/src/main/java/com/otgflasher/pro/MainActivity.java","w").write('package com.otgflasher.pro;\nimport android.app.Activity;\nimport android.os.Bundle;\nimport android.content.Intent;\npublic class MainActivity extends Activity{\n@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);\nfindViewById(R.id.cFastboot).setOnClickListener(v->startActivity(new Intent(this, FastbootActivity.class)));\nfindViewById(R.id.cMtk).setOnClickListener(v->startActivity(new Intent(this, MtkActivity.class)));\nfindViewById(R.id.cEdl).setOnClickListener(v->startActivity(new Intent(this, EdlActivity.class)));\nfindViewById(R.id.cOdin).setOnClickListener(v->startActivity(new Intent(this, OdinActivity.class)));\nfindViewById(R.id.cSpd).setOnClickListener(v->startActivity(new Intent(this, SpdActivity.class)));\nfindViewById(R.id.cPayload).setOnClickListener(v->startActivity(new Intent(this, PayloadActivity.class)));\nfindViewById(R.id.cSuper).setOnClickListener(v->startActivity(new Intent(this, SuperActivity.class)));\nfindViewById(R.id.cOfp).setOnClickListener(v->startActivity(new Intent(this, OfpActivity.class)));\nfindViewById(R.id.cFrp).setOnClickListener(v->startActivity(new Intent(this, FrpActivity.class)));\nfindViewById(R.id.cMi).setOnClickListener(v->startActivity(new Intent(this, MiActivity.class)));\nfindViewById(R.id.cQcn).setOnClickListener(v->startActivity(new Intent(this, QcnActivity.class)));\nfindViewById(R.id.cKg).setOnClickListener(v->startActivity(new Intent(this, KgActivity.class)));\nfindViewById(R.id.cUnlock).setOnClickListener(v->startActivity(new Intent(this, UnlockActivity.class)));\nfindViewById(R.id.cPart).setOnClickListener(v->startActivity(new Intent(this, PartActivity.class)));\n}}')

# FULL JAVA TEMPLATE
jt='''package com.otgflasher.pro;
import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;
public class CLASS extends Activity{
TextView txtDetail,log;ProgressBar bar;
@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.LAY);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());
CMDS
}
void run(String c){bar.setProgress(5);log.append("\\n> "+c+"\\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=3;if(pr>95) pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\\n"));}}).start();}
}
'''
def j(cls, lay, cmdlist):
    code=""
    for txt, shell in cmdlist:
        safe=txt.replace(" ","_").replace("/","_").replace("+","_")
        code+=f'findViewById(R.id.btn_{safe}).setOnClickListener(v->run("{shell}"));\n'
    content=jt.replace("CLASS",cls).replace("LAY",lay).replace("CMDS",code)
    open(f"app/src/main/java/com/otgflasher/pro/{cls}.java","w").write(content)

j("FastbootActivity","activity_fastboot",[("FLASH boot_a","fastboot flash boot_a /sdcard/Download/boot.img"),("FLASH boot_b","fastboot flash boot_b /sdcard/Download/boot.img"),("FLASH boot","fastboot flash boot /sdcard/Download/boot.img"),("FLASH recovery","fastboot flash recovery /sdcard/Download/recovery.img"),("FLASH vbmeta","fastboot flash vbmeta /sdcard/Download/vbmeta.img"),("FLASH vbmeta_a","fastboot flash vbmeta_a /sdcard/Download/vbmeta.img"),("FLASH super","fastboot flash super /sdcard/Download/super.img"),("FLASH system","fastboot flash system /sdcard/Download/system.img"),("ERASE frp","fastboot erase frp"),("ERASE userdata","fastboot erase userdata"),("SET ACTIVE A","fastboot --set-active=a"),("SET ACTIVE B","fastboot --set-active=b"),("REBOOT bootloader","fastboot reboot bootloader"),("REBOOT system","fastboot reboot"),("UNLOCK BL","fastboot flashing unlock"),("LOCK BL","fastboot flashing lock"),("OEM device-info","fastboot oem device-info")])
j("MtkActivity","activity_mtk",[("BYPASS AUTH SLA DAA","python3 -m mtk payload"),("FLASH Download Only","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt"),("FLASH Firmware Upgrade","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --firmware-upgrade"),("FLASH Format All + Download","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --format-all"),("READBACK boot 0x0 0x2000000","python3 -m mtk r boot /sdcard/Download/boot.img"),("READBACK preloader","python3 -m mtk r preloader /sdcard/Download/preloader.bin"),("FORMAT frp + userdata","python3 -m mtk e frp,userdata"),("FORMAT all","python3 -m mtk e frp,userdata,cache"),("ERASE FRP","python3 -m mtk e frp"),("DUMP preloader","python3 -m mtk r preloader /sdcard/Download/dump_preloader.bin"),("REBOOT","python3 -m mtk reset")])
j("EdlActivity","activity_edl",[("SAHARA TEST","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara"),("PRINT GPT UFS","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"),("PRINT GPT EMMC","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=emmc --printgpt"),("FLASH QFIL rawprogram+patch","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --rawprogram=/sdcard/Download/rawprogram0.xml --patch=/sdcard/Download/patch0.xml --memory=ufs"),("READ frp 100MB","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=frp --filename=/sdcard/Download/frp.img"),("ERASE frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"),("ERASE userdata","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=userdata"),("BACKUP QCN modemst1 modemst2 fsg","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img; dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img; dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img"),("RESTORE QCN","dd if=/sdcard/Download/modemst1.img of=/dev/block/bootdevice/by-name/modemst1"),("RESET EDL to normal","edl reset"),("READ full dump","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=userdata --filename=/sdcard/Download/userdata.img")])
j("OdinActivity","activity_odin",[("FLASH AP only","heimdall flash --AP /sdcard/Download/AP.tar.md5"),("FLASH BL only","heimdall flash --BL /sdcard/Download/BL.tar.md5"),("FLASH CP only","heimdall flash --CP /sdcard/Download/CP.tar.md5"),("FLASH CSC only","heimdall flash --CSC /sdcard/Download/CSC.tar.md5"),("FLASH AP+BL+CP+CSC FULL","heimdall flash --AP /sdcard/Download/AP.tar.md5 --BL /sdcard/Download/BL.tar.md5 --CP /sdcard/Download/CP.tar.md5 --CSC /sdcard/Download/CSC.tar.md5"),("READ PIT","heimdall print-pit"),("WRITE PIT","heimdall flash --pit /sdcard/Download/pit.pit"),("BYPASS KG knoxguard","adb shell pm disable-user --user 0 com.samsung.android.kgclient; adb shell pm disable-user --user 0 com.samsung.android.knoxguard"),("BYPASS MDM","adb shell pm disable-user --user 0 com.samsung.android.mdm"),("FRP BYPASS adb","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1; adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"),("REBOOT download","adb reboot download"),("REBOOT system","adb reboot")])
j("SpdActivity","activity_spd",[("FLASH PAC full","python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac"),("FLASH PAC format all","python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac --format-all"),("READ INFO","python3 /sdcard/Download/spd_info.py"),("READ FLASH","python3 /sdcard/Download/spd_read.py"),("FORMAT","python3 /sdcard/Download/spd_format.py"),("BYPASS FRP","python3 /sdcard/Download/spd_frp.py"),("DIAG","python3 /sdcard/Download/spd_diag.py")])
j("PayloadActivity","activity_payload",[("LIST partitions in payload","python3 -m payload_dumper --list /sdcard/Download/payload.bin"),("EXTRACT ALL","python3 -m payload_dumper /sdcard/Download/payload.bin --out /sdcard/Download/out/"),("EXTRACT boot","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions boot --out /sdcard/Download/out/"),("EXTRACT system","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions system --out /sdcard/Download/out/"),("EXTRACT vendor","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions vendor --out /sdcard/Download/out/"),("EXTRACT super","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions super --out /sdcard/Download/out/"),("EXTRACT dtbo","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions dtbo --out /sdcard/Download/out/"),("EXTRACT vbmeta","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions vbmeta --out /sdcard/Download/out/")])
j("SuperActivity","activity_super",[("LIST inside super lpdump","lpdump /sdcard/Download/super.img"),("UNPACK ALL lpunpack","lpunpack /sdcard/Download/super.img /sdcard/Download/out/"),("EXTRACT system.img","cp /sdcard/Download/out/system.img /sdcard/Download/system.img"),("EXTRACT vendor.img","cp /sdcard/Download/out/vendor.img /sdcard/Download/vendor.img"),("EXTRACT product.img","cp /sdcard/Download/out/product.img /sdcard/Download/product.img"),("MOUNT system","mkdir -p /mnt/system; mount -o loop /sdcard/Download/out/system.img /mnt/system"),("RESIZE super","lpresize /sdcard/Download/super.img"),("FLASH super","fastboot flash super /sdcard/Download/super.img")])
j("OfpActivity","activity_ofp",[("EXTRACT OFP all","python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/"),("EXTRACT OFP super only","python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/ --only super"),("DECRYPT OFP","python3 /sdcard/Download/ofp_decrypt.py /sdcard/Download/firmware.ofp"),("LIST OFP","python3 /sdcard/Download/ofp_extractor.py --list /sdcard/Download/firmware.ofp"),("FLASH OFP","echo flashing ofp extracted via fastboot")])
j("FrpActivity","activity_frp",[("ADB FRP settings secure user_setup_complete 1","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"),("ADB FRP remove accounts.db","adb shell rm /data/system/users/0/accounts.db; adb shell rm /data/system/users/0/accounts_ce.db"),("ADB FRP pm clear gsf login","adb shell pm clear com.google.android.gsf.login; adb shell pm clear com.google.android.gms"),("FASTBOOT ERASE frp","fastboot erase frp"),("FASTBOOT ERASE config","fastboot erase config"),("FASTBOOT ERASE persist","fastboot erase persist"),("MTK ERASE frp + nvram","python3 -m mtk e frp,nvram,nvdata"),("EDL ERASE frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"),("SAMSUNG FRP via adb + cp","adb shell am start -n com.google.android.gsf.login/com.google.android.gsf.login.LoginActivity"),("UNIVERSAL FRP bypass","adb shell am start -a android.intent.action.VIEW -d https://www.google.com"),("RESET FRP","fastboot erase frp; fastboot erase config")])
j("MiActivity","activity_mi",[("DISABLE FindDevice pm disable","adb shell pm disable-user --user 0 com.xiaomi.finddevice"),("ERASE micloud data/system/micloud","adb shell rm -rf /data/system/micloud; adb shell rm -rf /data/system/users/0/micloud"),("DISABLE micloud settings","adb shell settings put secure micloud_status 0; adb shell settings put secure find_device_enabled 0"),("ERASE frp","fastboot erase frp"),("ERASE persist","fastboot erase persist"),("BYPASS Mi Account via adb","adb shell pm disable-user --user 0 com.xiaomi.xmsf; adb shell pm disable-user --user 0 com.xiaomi.micloudsdk"),("REMOVE Mi Account persist.img","fastboot flash persist /sdcard/Download/persist.img"),("REBOOT","adb reboot")])
j("QcnActivity","activity_qcn",[("BACKUP QCN dd modemst1","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img bs=4096"),("BACKUP QCN dd modemst2","dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img bs=4096"),("BACKUP QCN dd fsg","dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img bs=4096"),("BACKUP QCN dd fsc","dd if=/dev/block/bootdevice/by-name/fsc of=/sdcard/Download/fsc.img bs=4096"),("BACKUP FULL QCN 4 files","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/qcn_full/modemst1.img; dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/qcn_full/modemst2.img; dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/qcn_full/fsg.img; dd if=/dev/block/bootdevice/by-name/fsc of=/sdcard/Download/qcn_full/fsc.img"),("RESTORE QCN modemst1","dd if=/sdcard/Download/modemst1.img of=/dev/block/bootdevice/by-name/modemst1 bs=4096"),("RESTORE QCN modemst2","dd if=/sdcard/Download/modemst2.img of=/dev/block/bootdevice/by-name/modemst2 bs=4096"),("RESTORE QCN fsg","dd if=/sdcard/Download/fsg.img of=/dev/block/bootdevice/by-name/fsg bs=4096"),("BACKUP EFS","dd if=/dev/block/bootdevice/by-name/efs1 of=/sdcard/Download/efs1.img; dd if=/dev/block/bootdevice/by-name/efs2 of=/sdcard/Download/efs2.img"),("RESTORE EFS","dd if=/sdcard/Download/efs1.img of=/dev/block/bootdevice/by-name/efs1"),("DIAG enable","adb shell setprop sys.usb.config diag,adb; adb shell setprop persist.usb.config diag,adb")])
j("KgActivity","activity_kg",[("DISABLE KGCLIENT pm disable","adb shell pm disable-user --user 0 com.samsung.android.kgclient"),("DISABLE MDM pm disable","adb shell pm disable-user --user 0 com.samsung.android.mdm; adb shell pm disable-user --user 0 com.samsung.android.mdm.service"),("DISABLE KNOX pm disable knox","adb shell pm disable-user --user 0 com.samsung.knox.kpecore; adb shell pm disable-user --user 0 com.samsung.knox.securefolder"),("REMOVE KGCLIENT uninstall","adb shell pm uninstall -k --user 0 com.samsung.android.kgclient"),("REMOVE MDM","adb shell pm uninstall -k --user 0 com.samsung.android.mdm"),("BYPASS KG via adb shell settings","adb shell settings put secure kg_state 0; adb shell settings put secure kg_locked 0"),("BYPASS KG via build.prop","adb shell setprop ro.config.knox 0; adb shell setprop ro.config.kg 0"),("DISABLE KG via samfw","adb shell am start -n com.samfw.frp/com.samfw.frp.MainActivity"),("RESET KG","adb shell pm clear com.samsung.android.kgclient; adb reboot")])
j("UnlockActivity","activity_unlock",[("CHECK BL status fastboot oem device-info","fastboot oem device-info; fastboot getvar unlocked; fastboot flashing get_unlock_ability"),("UNLOCK flashing unlock","fastboot flashing unlock"),("UNLOCK flashing unlock_critical","fastboot flashing unlock_critical"),("UNLOCK oem unlock","fastboot oem unlock"),("UNLOCK oem unlock-go","fastboot oem unlock-go"),("LOCK flashing lock","fastboot flashing lock"),("LOCK flashing lock_critical","fastboot flashing lock_critical"),("MTK UNLOCK","python3 -m mtk da seccfg unlock; python3 -m mtk xflash seccfg unlock"),("SAMSUNG UNLOCK via oem unlock","adb shell svc oem unlock; fastboot oem unlock"),("RELOCK","fastboot flashing lock; fastboot oem lock")])
j("PartActivity","activity_part",[("PRINT GPT sgdisk --print sda","sgdisk --print /dev/block/sda; sgdisk --print /dev/block/sdb"),("PRINT GPT gdisk","gdisk -l /dev/block/sda"),("PRINT partitions parted","parted /dev/block/sda print"),("BACKUP GPT sda 34 sectors","dd if=/dev/block/sda of=/sdcard/Download/gpt_backup.img bs=512 count=34"),("RESTORE GPT","dd if=/sdcard/Download/gpt_backup.img of=/dev/block/sda bs=512 count=34"),("BACKUP all partitions list","ls -l /dev/block/bootdevice/by-name/ > /sdcard/Download/part_list.txt; cat /sdcard/Download/part_list.txt"),("ERASE partition frp","sgdisk --delete 1 /dev/block/sda; fastboot erase frp"),("RESIZE super","lpresize /dev/block/super 0; lpresize /sdcard/Download/super.img 0"),("CREATE partition","sgdisk --new=1:0:0 --typecode=1:8300 /dev/block/sda"),("DELETE partition","sgdisk --delete 1 /dev/block/sda"),("BACKUP super","dd if=/dev/block/super of=/sdcard/Download/super_backup.img bs=4096")])

print("v20 FULL TOOLS COMPLETE")
