import os, re
os.makedirs("app/src/main/java/com/otgflasher/pro",exist_ok=True)
os.makedirs("app/src/main/res/layout",exist_ok=True)
os.makedirs("app/src/main/res/values",exist_ok=True)

def safe_id(s):
    s = re.sub(r'[^A-Za-z0-9_]', '_', s)
    s = re.sub(r'_+', '_', s)
    if s[0].isdigit():
        s = '_' + s
    return s[:50]

open("app/build.gradle","w").write("plugins{ id 'com.android.application' }\nandroid{ compileSdk 34; namespace 'com.otgflasher.pro'; defaultConfig{ applicationId 'com.otgflasher.pro'; minSdk 26; targetSdk 34; versionCode 23; versionName '23.0 PC FIX BUILD' } }\ndependencies{ implementation 'androidx.appcompat:appcompat:1.6.1' }\n")
open("app/src/main/res/values/strings.xml","w").write('<resources><string name="app_name">OTG Flasher v9 PC</string></resources>')
open("app/src/main/res/values/themes.xml","w").write('<resources><style name="Theme.OTGFlasher" parent="android:Theme.Material.Light.NoActionBar"/></resources>')
open("app/src/main/AndroidManifest.xml","w").write('<manifest xmlns:android="http://schemas.android.com/apk/res/android"><uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/><uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/><application android:theme="@style/Theme.OTGFlasher" android:label="OTG Flasher PC" android:requestLegacyExternalStorage="true"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><activity android:name=".MtkActivity"/><activity android:name=".FastbootActivity"/><activity android:name=".EdlActivity"/><activity android:name=".OdinActivity"/><activity android:name=".SpdActivity"/><activity android:name=".PayloadActivity"/><activity android:name=".SuperActivity"/><activity android:name=".OfpActivity"/><activity android:name=".FrpActivity"/><activity android:name=".MiActivity"/><activity android:name=".QcnActivity"/><activity android:name=".KgActivity"/><activity android:name=".UnlockActivity"/><activity android:name=".PartActivity"/><activity android:name=".AdbActivity"/><activity android:name=".SaharaActivity"/></application></manifest>')

main='''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#F5F5F5">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="70dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="14dp"><TextView android:text="OTG FLASHER v9 - 16 TOOLS PC FIX BUILD v23" android:textSize="16sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cFastboot" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="FASTBOOT PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMtk" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="MTK SP PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cEdl" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="EDL QFIL PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOdin" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="ODIN3 PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cSpd" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="SPD PAC PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPayload" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="PAYLOAD PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cSuper" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="SUPER PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOfp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="OFP PC" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cFrp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="FRP ALL PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMi" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="MI ACC PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cQcn" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="QCN EFS PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cKg" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="KG MDM PC" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cUnlock" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="UNLOCK BL PC" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPart" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="PARTITION PC" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cAdb" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="ADB TOOLS PC" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cSahara" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="110dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="SAHARA ROOT PC" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
</LinearLayout></ScrollView>'''
open("app/src/main/res/layout/activity_main.xml","w").write(main)

def make_layout(name, title, desc, file_fields, checks, buttons):
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#FFFFFF">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="60dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="10dp"><Button android:id="@+id/btnBack" android:text="BACK" android:layout_width="70dp" android:layout_height="44dp"/><TextView android:text="{title}" android:textSize="13sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:gravity="center"/></LinearLayout>
<TextView android:text="{desc}" android:textSize="11sp" android:background="#F5F5F5" android:padding="8dp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"/>
'''
    for ff in file_fields:
        sid = safe_id(ff)
        xml += f'<TextView android:text="{ff}" android:textSize="11sp" android:textStyle="bold" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp"/><LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="50dp" android:background="#EEEEEE" android:gravity="center_vertical" android:padding="8dp"><TextView android:id="@+id/txt_{sid}" android:text="/sdcard/Download/" android:textSize="10sp" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"/><Button android:id="@+id/btn_{sid}" android:text="BROWSE" android:layout_width="80dp" android:layout_height="38dp" android:textSize="10sp"/></LinearLayout>\n'
    xml += '<TextView android:text="OPTIONS:" android:textSize="11sp" android:textStyle="bold" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="12dp"/>\n'
    for ch in checks:
        sid = safe_id(ch)
        xml += f'<CheckBox android:id="@+id/cb_{sid}" android:text="{ch}" android:layout_width="match_parent" android:layout_height="wrap_content" android:textSize="11sp"/>\n'
    xml += '<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp">\n'
    for bt in buttons:
        sid = safe_id(bt)
        xml += f'<Button android:id="@+id/btn_{sid}" android:text="{bt[0]}" android:layout_width="match_parent" android:layout_height="58dp" android:textSize="11sp" android:layout_marginTop="5dp" android:backgroundTint="#2ECC71"/>\n'
    xml += '</LinearLayout>\n<ProgressBar android:id="@+id/progressBar" style="?android:attr/progressBarStyleHorizontal" android:layout_width="match_parent" android:layout_height="16dp" android:max="100" android:layout_marginTop="12dp"/>\n<TextView android:id="@+id/txtDetail" android:text="Ready PC" android:textSize="11sp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="5dp"/>\n<TextView android:id="@+id/logView" android:text="LOG PC" android:textSize="10sp" android:background="#111111" android:textColor="#00FF00" android:padding="8dp" android:layout_width="match_parent" android:layout_height="400dp" android:layout_marginTop="8dp"/>\n</LinearLayout></ScrollView>'
    open(f"app/src/main/res/layout/activity_{name}.xml","w").write(xml)

# DEFINE 16 TOOLS FIX IDS
make_layout("mtk","MTK SP FLASH v5","Scatter+Auth+DA+Readback+Format+MemoryTest kaya PC",["Scatter MT6765_scatter.txt","Auth file","DA file","Preloader","Firmware folder"], ["DA DL All Checksum","Format All Download","Firmware Upgrade","Download Only","Bypass SLA DAA","USB Checksum","Storage EMMC","Storage UFS","Include Preloader"], [("BYPASS AUTH","b1"),("DOWNLOAD ONLY","b2"),("FIRMWARE UPGRADE","b3"),("FORMAT ALL DOWNLOAD","b4"),("READBACK ADD","b5"),("READBACK boot","b6"),("READBACK preloader","b7"),("READBACK nvram","b8"),("FORMAT Auto","b9"),("FORMAT Manual frp","b10"),("FORMAT whole flash","b11"),("MEMORY TEST","b12"),("ERASE FRP","b13"),("ERASE FRP userdata","b14")])
make_layout("fastboot","FASTBOOT PC FULL","Fastboot PC all partitions",["boot img","super img","vbmeta img"], ["Disable Verity","Disable Verification","Slot A","Slot B"], [("FLASH boot_a",""),("FLASH boot_b",""),("FLASH boot",""),("FLASH recovery",""),("FLASH vbmeta",""),("FLASH super",""),("FLASH system",""),("FLASH vendor",""),("ERASE frp",""),("ERASE userdata",""),("GETVAR all",""),("OEM device info",""),("FLASHING unlock",""),("FLASHING lock",""),("REBOOT bootloader",""),("REBOOT edl","")])
make_layout("edl","EDL QFIL PC","QFIL Flat Build",["Programmer elf","Rawprogram xml","Patch xml"], ["Erase Before","Reset After","UFS","EMMC"], [("SAHARA TEST",""),("PRINT GPT UFS",""),("PRINT GPT EMMC",""),("PARTITION MANAGER",""),("FLASH Flat Build",""),("READ frp",""),("ERASE frp",""),("BACKUP QCN",""),("RESTORE QCN","")])
make_layout("odin","ODIN3 PC","Odin AP BL CP CSC PIT",["AP tar md5","BL tar md5","CP tar md5","CSC tar md5","PIT file"], ["Auto Reboot","Re Partition","F Reset Time","Nand Erase"], [("FLASH AP",""),("FLASH BL",""),("FLASH FULL",""),("READ PIT",""),("WRITE PIT",""),("BYPASS KG",""),("BYPASS MDM",""),("BYPASS FRP","")])
make_layout("spd","SPD PAC PC","SPD PAC",["PAC firmware pac"], ["Format All","Bypass NV"], [("FLASH PAC",""),("READ INFO",""),("FORMAT",""),("BYPASS FRP","")])
make_layout("payload","PAYLOAD PC","payload dumper",["payload bin","Output folder"], ["List only","Extract All"], [("LIST partitions",""),("EXTRACT ALL",""),("EXTRACT boot",""),("EXTRACT system","")])
make_layout("super","SUPER PC","lpunpack",["super img"], ["Sparse"], [("LPDUMP",""),("LPUNPACK all",""),("EXTRACT system",""),("FLASH super","")])
make_layout("ofp","OFP PC","OFP Extract",["firmware ofp"], ["Decrypt Only"], [("EXTRACT OFP all",""),("DECRYPT OFP",""),("LIST OFP","")])
make_layout("frp","FRP PC","FRP Bypass",["No file"], ["ADB","Fastboot","MTK"], [("ADB bypass",""),("FASTBOOT erase frp",""),("MTK erase frp",""),("EDL erase frp",""),("SAMSUNG bypass","")])
make_layout("mi","MI ACCOUNT PC","Mi Bypass",["persist img"], ["FindDevice"], [("DISABLE FindDevice",""),("ERASE micloud",""),("FLASH persist","")])
make_layout("qcn","QCN EFS PC","QCN Backup",["QCN file"], ["Backup All","UFS"], [("BACKUP modemst1",""),("BACKUP modemst2",""),("BACKUP fsg",""),("BACKUP FULL",""),("RESTORE",""),("DIAG enable","")])
make_layout("kg","KG MDM PC","KG Bypass",["No file"], ["KG","MDM","KNOX"], [("DISABLE KG",""),("DISABLE MDM",""),("DISABLE KNOX",""),("BYPASS settings","")])
make_layout("unlock","UNLOCK BL PC","Unlock BL",["No file"], ["Unlock","Lock"], [("CHECK status",""),("FLASHING unlock",""),("OEM unlock",""),("MTK seccfg unlock",""),("LOCK","")])
make_layout("part","PARTITION PC","Partition Manager",["No file"], ["UFS","GPT"], [("PRINT sgdisk",""),("PRINT gdisk",""),("BACKUP GPT",""),("ERASE frp",""),("BACKUP super","")])
make_layout("adb","ADB TOOLS PC","ADB PC",["APK file"], ["Root"], [("DEVICES",""),("SHELL",""),("LOGCAT",""),("INSTALL APK",""),("SCREENCAP",""),("REBOOT","")])
make_layout("sahara","SAHARA ROOT PC","Sahara Root",["boot img","magisk apk","twrp img"], ["Sahara v2","UFS"], [("SAHARA TEST",""),("DIAG enable",""),("ROOT magisk",""),("FLASH TWRP",""),("BROM bypass","")])

open("app/src/main/java/com/otgflasher/pro/MainActivity.java","w").write('package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.content.Intent;public class MainActivity extends Activity{@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);findViewById(R.id.cFastboot).setOnClickListener(v->startActivity(new Intent(this, FastbootActivity.class)));findViewById(R.id.cMtk).setOnClickListener(v->startActivity(new Intent(this, MtkActivity.class)));findViewById(R.id.cEdl).setOnClickListener(v->startActivity(new Intent(this, EdlActivity.class)));findViewById(R.id.cOdin).setOnClickListener(v->startActivity(new Intent(this, OdinActivity.class)));findViewById(R.id.cSpd).setOnClickListener(v->startActivity(new Intent(this, SpdActivity.class)));findViewById(R.id.cPayload).setOnClickListener(v->startActivity(new Intent(this, PayloadActivity.class)));findViewById(R.id.cSuper).setOnClickListener(v->startActivity(new Intent(this, SuperActivity.class)));findViewById(R.id.cOfp).setOnClickListener(v->startActivity(new Intent(this, OfpActivity.class)));findViewById(R.id.cFrp).setOnClickListener(v->startActivity(new Intent(this, FrpActivity.class)));findViewById(R.id.cMi).setOnClickListener(v->startActivity(new Intent(this, MiActivity.class)));findViewById(R.id.cQcn).setOnClickListener(v->startActivity(new Intent(this, QcnActivity.class)));findViewById(R.id.cKg).setOnClickListener(v->startActivity(new Intent(this, KgActivity.class)));findViewById(R.id.cUnlock).setOnClickListener(v->startActivity(new Intent(this, UnlockActivity.class)));findViewById(R.id.cPart).setOnClickListener(v->startActivity(new Intent(this, PartActivity.class)));findViewById(R.id.cAdb).setOnClickListener(v->startActivity(new Intent(this, AdbActivity.class)));findViewById(R.id.cSahara).setOnClickListener(v->startActivity(new Intent(this, SaharaActivity.class)));}}')

def j(cls, lay, cmds):
    code=""
    for txt in cmds:
        sid=safe_id(txt)
        code+=f'findViewById(R.id.btn_{sid}).setOnClickListener(v->run("{txt}"));\n'
    templ='''package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class CLS extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.LAY);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());CMDS}void run(String c){bar.setProgress(5);log.append("\\n> "+c+"\\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\\n"));}}).start();}}'''.replace("CLS",cls).replace("LAY",lay).replace("CMDS",code)
    open(f"app/src/main/java/com/otgflasher/pro/{cls}.java","w").write(templ)

j("MtkActivity","activity_mtk",["python3 -m mtk payload","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --firmware-upgrade","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --format-all","python3 -m mtk r boot /sdcard/Download/boot.img","python3 -m mtk r preloader /sdcard/Download/preloader.bin","python3 -m mtk r nvram /sdcard/Download/nvram.img","python3 -m mtk e frp,userdata,cache","python3 -m mtk e frp","python3 -m mtk da test","python3 -m mtk e frp,userdata"])
j("FastbootActivity","activity_fastboot",["fastboot flash boot_a /sdcard/Download/boot.img","fastboot flash boot /sdcard/Download/boot.img","fastboot flash recovery /sdcard/Download/recovery.img","fastboot flash vbmeta /sdcard/Download/vbmeta.img --disable-verity --disable-verification","fastboot flash super /sdcard/Download/super.img","fastboot flash system /sdcard/Download/system.img","fastboot erase frp","fastboot erase userdata","fastboot getvar all","fastboot oem device-info","fastboot flashing unlock","fastboot flashing lock","fastboot reboot bootloader","fastboot reboot edl"])
j("EdlActivity","activity_edl",["edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt --memory=emmc","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --rawprogram=/sdcard/Download/rawprogram0.xml --patch=/sdcard/Download/patch0.xml --memory=ufs","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=frp --filename=/sdcard/Download/frp.img","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img"])
j("OdinActivity","activity_odin",["heimdall flash --AP /sdcard/Download/AP.tar.md5","heimdall flash --BL /sdcard/Download/BL.tar.md5","heimdall flash --AP /sdcard/Download/AP.tar.md5 --BL /sdcard/Download/BL.tar.md5 --CP /sdcard/Download/CP.tar.md5 --CSC /sdcard/Download/CSC.tar.md5","heimdall print-pit","heimdall download-pit --output /sdcard/Download/pit.pit","adb shell pm disable-user --user 0 com.samsung.android.kgclient","adb shell pm disable-user --user 0 com.samsung.android.mdm","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"])
j("SpdActivity","activity_spd",["python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac","python3 /sdcard/Download/spd_info.py","python3 /sdcard/Download/spd_format.py"])
j("PayloadActivity","activity_payload",["python3 -m payload_dumper --list /sdcard/Download/payload.bin","python3 -m payload_dumper /sdcard/Download/payload.bin --out /sdcard/Download/out/","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions boot --out /sdcard/Download/out/"])
j("SuperActivity","activity_super",["lpdump /sdcard/Download/super.img","lpunpack /sdcard/Download/super.img /sdcard/Download/out/","fastboot flash super /sdcard/Download/super.img"])
j("OfpActivity","activity_ofp",["python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/","python3 /sdcard/Download/ofp_decrypt.py /sdcard/Download/firmware.ofp"])
j("FrpActivity","activity_frp",["adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1","fastboot erase frp","python3 -m mtk e frp,userdata","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"])
j("MiActivity","activity_mi",["adb shell pm disable-user --user 0 com.xiaomi.finddevice","adb shell rm -rf /data/system/micloud","fastboot flash persist /sdcard/Download/persist.img"])
j("QcnActivity","activity_qcn",["dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img","dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img","dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img","dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img","adb shell setprop sys.usb.config diag,adb"])
j("KgActivity","activity_kg",["adb shell pm disable-user --user 0 com.samsung.android.kgclient","adb shell pm disable-user --user 0 com.samsung.android.mdm","adb shell pm disable-user --user 0 com.samsung.knox.kpecore","adb shell settings put secure kg_state 0"])
j("UnlockActivity","activity_unlock",["fastboot oem device-info; fastboot getvar unlocked","fastboot flashing unlock","fastboot oem unlock","python3 -m mtk da seccfg unlock","fastboot flashing lock"])
j("PartActivity","activity_part",["sgdisk --print /dev/block/sda","gdisk -l /dev/block/sda","dd if=/dev/block/sda of=/sdcard/Download/gpt_backup.img bs=512 count=34","fastboot erase frp","dd if=/dev/block/super of=/sdcard/Download/super_backup.img"])
j("AdbActivity","activity_adb",["adb devices","adb shell","adb logcat","adb install /sdcard/Download/app.apk","adb shell screencap /sdcard/Download/screen.png","adb reboot"])
j("SaharaActivity","activity_sahara",["edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt","adb shell setprop sys.usb.config diag,adb","python3 /sdcard/Download/magisk_patch.py /sdcard/Download/boot.img","fastboot flash recovery /sdcard/Download/twrp.img","python3 -m mtk payload"])

print("v23 FIX BUILD DONE - NO PLUS IN ID")
