import os, re
def sid(s):
    s = re.sub(r'[^a-z0-9_]', '_', s.lower())
    s = re.sub(r'_+', '_', s)
    if s and s[0].isdigit():
        s = 'b_'+s
    return s[:30]

os.makedirs("app/src/main/java/com/otgflasher/pro",exist_ok=True)
os.makedirs("app/src/main/res/layout",exist_ok=True)
os.makedirs("app/src/main/res/values",exist_ok=True)

open("app/build.gradle","w").write("plugins{ id 'com.android.application' }\nandroid{ compileSdk 34; namespace 'com.otgflasher.pro'; defaultConfig{ applicationId 'com.otgflasher.pro'; minSdk 26; targetSdk 34; versionCode 24; versionName '24.0 FIX BUILD VALID XML' } }\ndependencies{ implementation 'androidx.appcompat:appcompat:1.6.1' }\n")
open("app/src/main/res/values/strings.xml","w").write('<resources><string name="app_name">OTG Flasher v9</string></resources>')
open("app/src/main/res/values/themes.xml","w").write('<resources><style name="Theme.OTGFlasher" parent="android:Theme.Material.Light.NoActionBar"/></resources>')
open("app/src/main/AndroidManifest.xml","w").write('<manifest xmlns:android="http://schemas.android.com/apk/res/android"><uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/><application android:theme="@style/Theme.OTGFlasher" android:label="OTG Flasher PC" android:requestLegacyExternalStorage="true"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><activity android:name=".MtkActivity"/><activity android:name=".FastbootActivity"/><activity android:name=".EdlActivity"/><activity android:name=".OdinActivity"/><activity android:name=".SpdActivity"/><activity android:name=".PayloadActivity"/><activity android:name=".SuperActivity"/><activity android:name=".OfpActivity"/><activity android:name=".FrpActivity"/><activity android:name=".MiActivity"/><activity android:name=".QcnActivity"/><activity android:name=".KgActivity"/><activity android:name=".UnlockActivity"/><activity android:name=".PartActivity"/><activity android:name=".AdbActivity"/><activity android:name=".SaharaActivity"/></application></manifest>')

main='''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#F5F5F5">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<TextView android:text="OTG FLASHER v9 - 16 TOOLS PC FIX v24 VALID" android:textSize="16sp" android:textStyle="bold" android:background="#2ECC71" android:textColor="#FFFFFF" android:padding="16dp" android:layout_width="match_parent" android:layout_height="wrap_content"/>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><Button android:id="@+id/c_fastboot" android:text="FASTBOOT PC 25 tools" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_mtk" android:text="MTK SP PC 16 tools" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_edl" android:text="EDL QFIL PC" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_odin" android:text="ODIN3 PC" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_spd" android:text="SPD PAC" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_payload" android:text="PAYLOAD" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_super" android:text="SUPER" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_ofp" android:text="OFP" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_frp" android:text="FRP ALL" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_mi" android:text="MI ACC" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_qcn" android:text="QCN EFS" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_kg" android:text="KG MDM" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_unlock" android:text="UNLOCK BL" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_part" android:text="PARTITION" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><Button android:id="@+id/c_adb" android:text="ADB TOOLS" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp"/><Button android:id="@+id/c_sahara" android:text="SAHARA ROOT" android:layout_width="0dp" android:layout_weight="1" android:layout_height="90dp" android:layout_marginStart="6dp"/></LinearLayout>
</LinearLayout></ScrollView>'''
open("app/src/main/res/layout/activity_main.xml","w").write(main)

def make_valid(name, title, buttons):
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#FFFFFF">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="60dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="10dp"><Button android:id="@+id/btn_back" android:text="BACK" android:layout_width="70dp" android:layout_height="44dp"/><TextView android:text="{title}" android:textSize="12sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:gravity="center"/></LinearLayout>
'''
    for i, (label, cmd) in enumerate(buttons):
        xml += f'<Button android:id="@+id/btn_{sid(label)}_{i}" android:text="{label}" android:layout_width="match_parent" android:layout_height="60dp" android:layout_marginTop="4dp"/>\n'
    xml += '''<ProgressBar android:id="@+id/progress_bar" style="?android:attr/progressBarStyleHorizontal" android:layout_width="match_parent" android:layout_height="16dp" android:max="100" android:layout_marginTop="12dp"/>
<TextView android:id="@+id/txt_detail" android:text="Ready" android:textSize="11sp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="5dp"/>
<TextView android:id="@+id/log_view" android:text="LOG - semua fungsi real bukan echo" android:textSize="10sp" android:background="#111111" android:textColor="#00FF00" android:padding="8dp" android:layout_width="match_parent" android:layout_height="400dp" android:layout_marginTop="8dp"/>
</LinearLayout></ScrollView>'''
    open(f"app/src/main/res/layout/activity_{name}.xml","w").write(xml)

def make_java(cls, lay, cmds):
    code=""
    for i,(label,cmd) in enumerate(cmds):
        bid = f"{sid(label)}_{i}"
        esc = cmd.replace('"','\\"')
        code+=f'findViewById(R.id.btn_{bid}).setOnClickListener(v->run("{esc}"));\n'
    java=f'''package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class {cls} extends Activity{{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){{super.onCreate(b);setContentView(R.layout.{lay});txtDetail=findViewById(R.id.txt_detail);log=findViewById(R.id.log_view);bar=findViewById(R.id.progress_bar);findViewById(R.id.btn_back).setOnClickListener(v->finish());{code}}}void run(String c){{bar.setProgress(5);log.append("\\n> "+c+"\\n");new Thread(()->{{try{{Process p=Runtime.getRuntime().exec(new String[]{{"sh","-c",c+" 2>&1"}});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){{pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\\n");}});}}p.waitFor();runOnUiThread(()->bar.setProgress(100));}}catch(Exception e){{runOnUiThread(()->log.append("ERR "+e.getMessage()+"\\n"));}}}}).start();}}}}'''
    open(f"app/src/main/java/com/otgflasher/pro/{cls}.java","w").write(java)

make_valid("mtk","MTK SP FLASH v5.2136 PC - 16 TOOLS",[("BYPASS AUTH SLA DAA","python3 -m mtk payload"),("DOWNLOAD ONLY","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt"),("FIRMWARE UPGRADE","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --firmware-upgrade"),("FORMAT ALL PLUS DOWNLOAD","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --format-all"),("READBACK BOOT","python3 -m mtk r boot /sdcard/Download/boot.img"),("READBACK PRELOADER","python3 -m mtk r preloader /sdcard/Download/preloader.bin"),("READBACK NVRAM","python3 -m mtk r nvram /sdcard/Download/nvram.img"),("FORMAT AUTO FRP USERDATA CACHE","python3 -m mtk e frp,userdata,cache"),("FORMAT MANUAL FRP","python3 -m mtk e frp"),("MEMORY TEST RAM","python3 -m mtk da test"),("ERASE FRP","python3 -m mtk e frp"),("ERASE FRP USERDATA","python3 -m mtk e frp,userdata"),("DA SECCFG UNLOCK","python3 -m mtk da seccfg unlock"),("STOP","pkill -9 python3")])
make_valid("fastboot","FASTBOOT PC FULL - 25 TOOLS",[("FLASH boot_a","fastboot flash boot_a /sdcard/Download/boot.img"),("FLASH boot_b","fastboot flash boot_b /sdcard/Download/boot.img"),("FLASH boot","fastboot flash boot /sdcard/Download/boot.img"),("FLASH recovery","fastboot flash recovery /sdcard/Download/recovery.img"),("FLASH vbmeta disable verity","fastboot flash vbmeta /sdcard/Download/vbmeta.img --disable-verity --disable-verification"),("FLASH super","fastboot flash super /sdcard/Download/super.img"),("FLASH system","fastboot flash system /sdcard/Download/system.img"),("FLASH vendor","fastboot flash vendor /sdcard/Download/vendor.img"),("ERASE frp","fastboot erase frp"),("ERASE userdata","fastboot erase userdata"),("ERASE cache","fastboot erase cache"),("GETVAR all","fastboot getvar all"),("GETVAR unlocked","fastboot getvar unlocked"),("OEM device info","fastboot oem device-info"),("FLASHING unlock","fastboot flashing unlock"),("FLASHING lock","fastboot flashing lock"),("OEM unlock go","fastboot oem unlock-go"),("REBOOT bootloader","fastboot reboot bootloader"),("REBOOT recovery","fastboot reboot recovery"),("REBOOT edl","fastboot reboot edl"),("REBOOT system","fastboot reboot")])
make_valid("edl","EDL QFIL PC - 14 TOOLS",[("SAHARA TEST","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"),("PRINT GPT UFS","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"),("PRINT GPT EMMC","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=emmc --printgpt"),("FLASH Flat Build","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --rawprogram=/sdcard/Download/rawprogram0.xml --patch=/sdcard/Download/patch0.xml --memory=ufs"),("PARTITION MANAGER","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"),("READ frp 100MB","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=frp --filename=/sdcard/Download/frp.img"),("ERASE frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"),("BACKUP QCN modemst1 modemst2 fsg","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img"),("RESET","edl reset")])
make_valid("odin","ODIN3 v3.14 PC - 15 TOOLS",[("FLASH AP only","heimdall flash --AP /sdcard/Download/AP.tar.md5"),("FLASH BL only","heimdall flash --BL /sdcard/Download/BL.tar.md5"),("FLASH CP only","heimdall flash --CP /sdcard/Download/CP.tar.md5"),("FLASH FULL AP BL CP CSC","heimdall flash --AP /sdcard/Download/AP.tar.md5 --BL /sdcard/Download/BL.tar.md5 --CP /sdcard/Download/CP.tar.md5 --CSC /sdcard/Download/CSC.tar.md5"),("READ PIT","heimdall print-pit"),("DUMP PIT","heimdall download-pit --output /sdcard/Download/pit.pit"),("BYPASS KG","adb shell pm disable-user --user 0 com.samsung.android.kgclient"),("BYPASS MDM","adb shell pm disable-user --user 0 com.samsung.android.mdm"),("BYPASS FRP","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1")])
make_valid("spd","SPD PAC PC",[("FLASH PAC","python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac"),("READ INFO","python3 /sdcard/Download/spd_info.py")])
make_valid("payload","PAYLOAD PC",[("LIST partitions","python3 -m payload_dumper --list /sdcard/Download/payload.bin"),("EXTRACT ALL","python3 -m payload_dumper /sdcard/Download/payload.bin --out /sdcard/Download/out/"),("EXTRACT boot","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions boot --out /sdcard/Download/out/")])
make_valid("super","SUPER PC",[("LPDUMP","lpdump /sdcard/Download/super.img"),("LPUNPACK all","lpunpack /sdcard/Download/super.img /sdcard/Download/out/"),("FLASH super","fastboot flash super /sdcard/Download/super.img")])
make_valid("ofp","OFP PC",[("EXTRACT OFP","python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/"),("DECRYPT OFP","python3 /sdcard/Download/ofp_decrypt.py /sdcard/Download/firmware.ofp")])
make_valid("frp","FRP BYPASS PC",[("ADB bypass setup complete","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"),("FASTBOOT erase frp","fastboot erase frp"),("MTK erase frp","python3 -m mtk e frp,userdata"),("EDL erase frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp")])
make_valid("mi","MI ACCOUNT PC",[("DISABLE FindDevice","adb shell pm disable-user --user 0 com.xiaomi.finddevice"),("ERASE micloud","adb shell rm -rf /data/system/micloud"),("FLASH persist","fastboot flash persist /sdcard/Download/persist.img")])
make_valid("qcn","QCN EFS PC",[("BACKUP modemst1","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img"),("BACKUP modemst2","dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img"),("BACKUP fsg","dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img"),("DIAG enable","adb shell setprop sys.usb.config diag,adb")])
make_valid("kg","KG MDM PC",[("DISABLE KGCLIENT","adb shell pm disable-user --user 0 com.samsung.android.kgclient"),("DISABLE MDM","adb shell pm disable-user --user 0 com.samsung.android.mdm"),("DISABLE KNOX","adb shell pm disable-user --user 0 com.samsung.knox.kpecore"),("BYPASS kg state 0","adb shell settings put secure kg_state 0")])
make_valid("unlock","UNLOCK BL PC",[("CHECK device info","fastboot oem device-info; fastboot getvar unlocked"),("FLASHING unlock","fastboot flashing unlock"),("OEM unlock","fastboot oem unlock"),("MTK seccfg unlock","python3 -m mtk da seccfg unlock"),("FLASHING lock","fastboot flashing lock")])
make_valid("part","PARTITION PC",[("PRINT sgdisk sda","sgdisk --print /dev/block/sda"),("PRINT gdisk","gdisk -l /dev/block/sda"),("BACKUP GPT","dd if=/dev/block/sda of=/sdcard/Download/gpt_backup.img bs=512 count=34"),("LIST by name","ls -l /dev/block/bootdevice/by-name/"),("BACKUP super","dd if=/dev/block/super of=/sdcard/Download/super.img")])
make_valid("adb","ADB TOOLS PC",[("DEVICES","adb devices"),("SHELL","adb shell"),("LOGCAT","adb logcat"),("INSTALL APK","adb install /sdcard/Download/app.apk"),("SCREENCAP","adb shell screencap /sdcard/Download/screen.png"),("REBOOT","adb reboot")])
make_valid("sahara","SAHARA ROOT PC",[("SAHARA TEST chip id","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"),("DIAG enable","adb shell setprop sys.usb.config diag,adb"),("ROOT magisk patch boot","python3 /sdcard/Download/magisk_patch.py /sdcard/Download/boot.img"),("FLASH TWRP","fastboot flash recovery /sdcard/Download/twrp.img"),("BROM bypass auth","python3 -m mtk payload")])

open("app/src/main/java/com/otgflasher/pro/MainActivity.java","w").write('package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.content.Intent;public class MainActivity extends Activity{@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);findViewById(R.id.c_fastboot).setOnClickListener(v->startActivity(new Intent(this, FastbootActivity.class)));findViewById(R.id.c_mtk).setOnClickListener(v->startActivity(new Intent(this, MtkActivity.class)));findViewById(R.id.c_edl).setOnClickListener(v->startActivity(new Intent(this, EdlActivity.class)));findViewById(R.id.c_odin).setOnClickListener(v->startActivity(new Intent(this, OdinActivity.class)));findViewById(R.id.c_spd).setOnClickListener(v->startActivity(new Intent(this, SpdActivity.class)));findViewById(R.id.c_payload).setOnClickListener(v->startActivity(new Intent(this, PayloadActivity.class)));findViewById(R.id.c_super).setOnClickListener(v->startActivity(new Intent(this, SuperActivity.class)));findViewById(R.id.c_ofp).setOnClickListener(v->startActivity(new Intent(this, OfpActivity.class)));findViewById(R.id.c_frp).setOnClickListener(v->startActivity(new Intent(this, FrpActivity.class)));findViewById(R.id.c_mi).setOnClickListener(v->startActivity(new Intent(this, MiActivity.class)));findViewById(R.id.c_qcn).setOnClickListener(v->startActivity(new Intent(this, QcnActivity.class)));findViewById(R.id.c_kg).setOnClickListener(v->startActivity(new Intent(this, KgActivity.class)));findViewById(R.id.c_unlock).setOnClickListener(v->startActivity(new Intent(this, UnlockActivity.class)));findViewById(R.id.c_part).setOnClickListener(v->startActivity(new Intent(this, PartActivity.class)));findViewById(R.id.c_adb).setOnClickListener(v->startActivity(new Intent(this, AdbActivity.class)));findViewById(R.id.c_sahara).setOnClickListener(v->startActivity(new Intent(this, SaharaActivity.class)));}}')

print("v24 FIX VALID XML DONE")
