import os
os.makedirs("app/src/main/java/com/otgflasher/pro",exist_ok=True)
os.makedirs("app/src/main/res/layout",exist_ok=True)
os.makedirs("app/src/main/res/values",exist_ok=True)
open("app/build.gradle","w").write("plugins{ id 'com.android.application' }\nandroid{ compileSdk 34; namespace 'com.otgflasher.pro'; defaultConfig{ applicationId 'com.otgflasher.pro'; minSdk 26; targetSdk 34; versionCode 22; versionName '22.0 PC PARITY' } }\ndependencies{ implementation 'androidx.appcompat:appcompat:1.6.1' }\n")
open("app/src/main/res/values/strings.xml","w").write('<resources><string name="app_name">OTG Flasher v9 PC</string></resources>')
open("app/src/main/res/values/themes.xml","w").write('<resources><style name="Theme.OTGFlasher" parent="android:Theme.Material.Light.NoActionBar"/></resources>')
open("app/src/main/AndroidManifest.xml","w").write('<manifest xmlns:android="http://schemas.android.com/apk/res/android"><uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/><uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/><application android:theme="@style/Theme.OTGFlasher" android:label="OTG Flasher PC" android:requestLegacyExternalStorage="true"><activity android:name=".MainActivity" android:exported="true"><intent-filter><action android:name="android.intent.action.MAIN"/><category android:name="android.intent.category.LAUNCHER"/></intent-filter></activity><activity android:name=".MtkActivity"/><activity android:name=".FastbootActivity"/><activity android:name=".EdlActivity"/><activity android:name=".OdinActivity"/><activity android:name=".SpdActivity"/><activity android:name=".PayloadActivity"/><activity android:name=".SuperActivity"/><activity android:name=".OfpActivity"/><activity android:name=".FrpActivity"/><activity android:name=".MiActivity"/><activity android:name=".QcnActivity"/><activity android:name=".KgActivity"/><activity android:name=".UnlockActivity"/><activity android:name=".PartActivity"/><activity android:name=".AdbActivity"/><activity android:name=".SaharaActivity"/></application></manifest>')

main='''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#F5F5F5">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="70dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="14dp"><TextView android:text="OTG FLASHER v9 - 16 TOOLS PC PARITY" android:textSize="16sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"/></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"><LinearLayout android:id="@+id/cFastboot" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="FASTBOOT\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMtk" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="MTK SP\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cEdl" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="EDL QFIL\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOdin" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="ODIN3\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cSpd" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="SPD PAC\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPayload" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="PAYLOAD\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cSuper" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="SUPER\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cOfp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="OFP\nPC FULL" android:textSize="14sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cFrp" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="FRP ALL\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cMi" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="MI ACC\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cQcn" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="QCN EFS\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cKg" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="KG MDM\nPC FULL" android:textSize="13sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cUnlock" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="UNLOCK BL\nPC FULL" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cPart" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="PARTITION\nPC FULL" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="6dp"><LinearLayout android:id="@+id/cAdb" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp"><TextView android:text="ADB TOOLS\nPC FULL" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout><LinearLayout android:id="@+id/cSahara" android:orientation="vertical" android:layout_width="0dp" android:layout_weight="1" android:layout_height="120dp" android:background="#FFFFFF" android:gravity="center" android:elevation="3dp" android:layout_marginStart="6dp"><TextView android:text="SAHARA ROOT\nPC FULL" android:textSize="12sp" android:textStyle="bold" android:gravity="center" android:layout_width="wrap_content" android:layout_height="wrap_content"/></LinearLayout></LinearLayout>
</LinearLayout></ScrollView>'''
open("app/src/main/res/layout/activity_main.xml","w").write(main)

def full_layout(name,title,desc,fields,checks,buttons):
    fxml=""
    for fld in fields:
        idf=fld.replace(" ","_").replace("/","_")
        fxml+=f'<TextView android:text="{fld}" android:textSize="11sp" android:textStyle="bold" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp"/><LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="50dp" android:background="#EEEEEE" android:gravity="center_vertical" android:padding="8dp"><TextView android:id="@+id/txt_{idf}" android:text="/sdcard/Download/" android:textSize="10sp" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content"/><Button android:id="@+id/btn_{idf}" android:text="BROWSE" android:layout_width="80dp" android:layout_height="38dp" android:textSize="10sp"/></LinearLayout>\n'
    cxml=""
    for ch in checks:
        idc=ch.replace(" ","_")
        cxml+=f'<CheckBox android:id="@+id/cb_{idc}" android:text="{ch}" android:layout_width="match_parent" android:layout_height="wrap_content" android:textSize="11sp"/>\n'
    bxml=""
    for bt in buttons:
        idb=bt.replace(" ","_").replace("/","_").replace("+","_")
        bxml+=f'<Button android:id="@+id/btn_{idb}" android:text="{bt}" android:layout_width="match_parent" android:layout_height="58dp" android:textSize="11sp" android:layout_marginTop="5dp" android:backgroundTint="#2ECC71"/>\n'
    xml=f'''<?xml version="1.0" encoding="utf-8"?>
<ScrollView xmlns:android="http://schemas.android.com/apk/res/android" android:layout_width="match_parent" android:layout_height="match_parent" android:background="#FFFFFF">
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:padding="10dp">
<LinearLayout android:orientation="horizontal" android:layout_width="match_parent" android:layout_height="60dp" android:background="#2ECC71" android:gravity="center_vertical" android:padding="10dp"><Button android:id="@+id/btnBack" android:text="BACK" android:layout_width="70dp" android:layout_height="44dp"/><TextView android:text="{title} - PC PARITY" android:textSize="13sp" android:textStyle="bold" android:textColor="#FFFFFF" android:layout_width="0dp" android:layout_weight="1" android:layout_height="wrap_content" android:gravity="center"/></LinearLayout>
<TextView android:text="{desc}" android:textSize="11sp" android:background="#F5F5F5" android:padding="8dp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="8dp"/>
{fxml}
<TextView android:text="OPTIONS (samain kaya PC):" android:textSize="11sp" android:textStyle="bold" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="12dp"/>
{cxml}
<LinearLayout android:orientation="vertical" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="10dp">
{bxml}
</LinearLayout>
<ProgressBar android:id="@+id/progressBar" style="?android:attr/progressBarStyleHorizontal" android:layout_width="match_parent" android:layout_height="16dp" android:max="100" android:layout_marginTop="12dp"/>
<TextView android:id="@+id/txtDetail" android:text="Ready PC Parity" android:textSize="11sp" android:layout_width="match_parent" android:layout_height="wrap_content" android:layout_marginTop="5dp"/>
<TextView android:id="@+id/logView" android:text="LOG {title} PC PARITY - semua fungsi jalan" android:textSize="10sp" android:background="#111111" android:textColor="#00FF00" android:padding="8dp" android:layout_width="match_parent" android:layout_height="400dp" android:layout_marginTop="8dp"/>
</LinearLayout></ScrollView>'''
    open(f"app/src/main/res/layout/activity_{name}.xml","w").write(xml)

# 16 TOOLS PC PARITY FULL
full_layout("mtk","MTK SP FLASH TOOL v5.2136","TAB Download/Readback/Format/Memory Test kaya PC - Scatter + Auth + DA + Preloader",["Scatter MT6765_scatter.txt","Auth file auth_sv5.auth","DA file MTK_AllInOne_DA.bin","Preloader preloader.bin","Firmware folder"], ["DA DL All with Checksum","Format All + Download","Firmware Upgrade","Download Only","Bypass SLA/DAA Auth","USB Checksum","Storage HW Default","Storage EMMC","Storage UFS","Include Preloader"], ["BYPASS AUTH SLA DAA","DOWNLOAD ONLY","FIRMWARE UPGRADE","FORMAT ALL + DOWNLOAD","READBACK ADD","READBACK boot 0x0 0x2000000","READBACK preloader","READBACK nvram","FORMAT Auto Format","FORMAT Manual Format frp 0x0 0x100000","FORMAT whole flash except bootloader","MEMORY TEST RAM","MEMORY TEST EMMC","ERASE FRP","ERASE FRP+userdata","STOP"])
full_layout("fastboot","FASTBOOT PC FULL","Minimal ADB Fastboot PC - semua partisi + oem",["File boot.img","File super.img","File vbmeta.img"], ["Disable Verity","Disable Verification","Slot A","Slot B","Set Active A","Set Active B"], ["FLASH boot_a","FLASH boot_b","FLASH boot","FLASH recovery","FLASH vbmeta","FLASH vbmeta_a","FLASH vbmeta_b","FLASH super","FLASH system","FLASH vendor","FLASH dtbo","FLASH modem","ERASE frp","ERASE userdata","ERASE cache","GETVAR all","GETVAR unlocked","OEM device-info","FLASHING unlock","FLASHING lock","OEM unlock-go","REBOOT bootloader","REBOOT recovery","REBOOT edl","REBOOT system"])
full_layout("edl","EDL QFIL PC FULL","QFIL v2.0.3.5 Flat Build + Tools Partition Manager",["Programmer prog_firehose_ddr.elf","Rawprogram rawprogram0.xml","Patch patch0.xml","Storage UFS/EMMC"], ["Erase All Before Download","Reset After Download","Flat Build","Meta Build","UFS","EMMC"], ["SAHARA TEST","SAHARA Upload","PRINT GPT UFS","PRINT GPT EMMC","PARTITION MANAGER","FLASH Flat Build rawprogram+patch","READ frp 100MB","READ userdata 1GB","ERASE frp","ERASE userdata","BACKUP QCN modemst1+modemst2+fsg","RESTORE QCN","RESET to normal","SELECT PORT COM"])
full_layout("odin","ODIN3 v3.14 PC FULL","Odin3 v3.14.4 - BL AP CP CSC PIT + Options",["AP file AP.tar.md5","BL file BL.tar.md5","CP file CP.tar.md5","CSC file CSC.tar.md5","HOME_CSC","PIT file"], ["Auto Reboot","Re-Partition","F.Reset Time","Nand Erase All","Flash Lock","T Flash","Phone EFS Clear","Phone Bootloader Update"], ["FLASH AP only","FLASH BL only","FLASH CP only","FLASH CSC only","FLASH HOME_CSC","FLASH FULL AP+BL+CP+CSC","READ PIT","WRITE PIT","DUMP PIT","BYPASS KG","BYPASS MDM","BYPASS FRP","ERASE Nand All","REBOOT Download","REBOOT System"])
full_layout("spd","SPD UPGRADE PC FULL","SPD Upgrade Tool - PAC + FDL",["PAC firmware.pac","FDL1","FDL2"], ["Bypass NV","Format All","Download Only","Auto Reboot"], ["FLASH PAC","FLASH PAC Format All","READ INFO","READ FLASH","FORMAT","BYPASS FRP","DIAG MODE","BACKUP PAC"])
full_layout("payload","PAYLOAD DUMPER PC FULL","payload_dumper PC - OTA payload.bin extractor",["payload.bin","Output folder out/"], ["List only","Extract All","Overwrite"], ["LIST partitions","EXTRACT ALL","EXTRACT boot","EXTRACT system","EXTRACT vendor","EXTRACT product","EXTRACT super","EXTRACT dtbo","EXTRACT vbmeta","EXTRACT odm","EXTRACT system_ext"])
full_layout("super","SUPER UNPACK PC FULL","lpunpack lpdump PC - super.img",["super.img","Output out/"], ["Sparse","Read Only"], ["LPDUMP list inside super","LPUNPACK all","EXTRACT system","EXTRACT vendor","EXTRACT product","EXTRACT system_ext","EXTRACT odm","MOUNT system","RESIZE super","LPMAKE new super","FLASH super fastboot"])
full_layout("ofp","OFP EXTRACT PC FULL","OPPO Realme OFP Decrypt PC",["firmware.ofp","Output out/"], ["Decrypt Only","Extract super only"], ["EXTRACT OFP all","EXTRACT super only","DECRYPT OFP","LIST OFP files","FLASH OFP extracted","CONVERT OFP to scatter"])
full_layout("frp","FRP BYPASS PC FULL","FRP Bypass All Methods PC - ADB Fastboot MTK EDL Samsung",["No file - device connected"], ["ADB","Fastboot","MTK","EDL","Samsung"], ["ADB settings user_setup_complete 1","ADB rm accounts.db","ADB pm clear gsf login+gms","FASTBOOT erase frp","FASTBOOT erase config","FASTBOOT erase persist","FASTBOOT erase frp+config+persist","MTK erase frp+nvram+nvdata","EDL erase frp","SAMSUNG Talkback bypass","SAMSUNG YouTube bypass","UNIVERSAL FRP am start google","RESET FRP"])
full_layout("mi","MI ACCOUNT PC FULL","Mi Account Bypass PC - FindDevice micloud",["persist.img","mi account file"], ["Disable FindDevice","Erase micloud"], ["DISABLE FindDevice pm disable","ERASE micloud data","DISABLE micloud settings","ERASE frp","ERASE persist","BYPASS Mi Account xmsf+micloudsdk","FLASH persist.img","REMOVE Mi Account persist","REBOOT"])
full_layout("qcn","QCN EFS PC FULL","QPST QFIL QCN Backup Restore PC",["QCN backup.qcn","EFS folder"], ["Backup All","Restore All","UFS","EMMC"], ["BACKUP modemst1 dd","BACKUP modemst2 dd","BACKUP fsg dd","BACKUP fsc dd","BACKUP efs1+efs2 dd","BACKUP FULL 4 files","RESTORE modemst1","RESTORE modemst2","RESTORE fsg","RESTORE efs1+efs2","DIAG enable diag,adb","QCN Rebuild"])
full_layout("kg","KG MDM KNOX PC FULL","SamFW KG MDM Bypass PC",["No file"], ["KGCLIENT","MDM","KNOX"], ["DISABLE KGCLIENT","DISABLE MDM service","DISABLE KNOX kpecore+securefolder","UNINSTALL KGCLIENT","UNINSTALL MDM","BYPASS settings kg_state 0","BYPASS build.prop ro.config.knox 0","SAMFW Tool FRP start","CLEAR KGCLIENT+reboot","RESET KG"])
full_layout("unlock","UNLOCK BL PC FULL","Unlock Bootloader PC - fastboot oem",["No file"], ["Unlock","Lock","Critical"], ["CHECK device-info+getvar unlocked+get_unlock_ability","FLASHING unlock","FLASHING unlock_critical","OEM unlock","OEM unlock-go","FLASHING lock","FLASHING lock_critical","OEM lock","MTK seccfg unlock","MTK xflash seccfg unlock","SAMSUNG OEM unlock","RELOCK"])
full_layout("part","PARTITION MANAGER PC FULL","Partition Manager PC - sgdisk gdisk parted",["No file"], ["UFS","EMMC","GPT"], ["PRINT sgdisk sda+sdb","PRINT gdisk -l sda","PRINT parted sda print","LIST by-name","BACKUP GPT 34 sectors","RESTORE GPT","BACKUP all partitions list","ERASE frp","ERASE userdata","RESIZE super lpresize 0","CREATE partition","DELETE partition","BACKUP super","FLASH super"])
full_layout("adb","ADB TOOLS PC FULL","ADB PC Full - devices shell logcat install",["APK file","File to push/pull"], ["Root","Remount","Verbose"], ["DEVICES adb devices","SHELL adb shell","LOGCAT adb logcat","INSTALL APK","PUSH file to sdcard","PULL file from sdcard","SCREENCAP","SCREENRECORD","REBOOT","REBOOT bootloader","REBOOT recovery","REBOOT edl","ROOT adb root","REMOUNT","DISABLE-VERITY","SHELL pm list packages"])
full_layout("sahara","SAHARA ROOT PC FULL","Sahara Diag Root Magisk TWRP PC",["boot.img","magisk apk","twrp.img","Firehose loader"], ["Sahara v2","Sahara v3","UFS","EMMC"], ["SAHARA TEST chip id","SAHARA Upload loader","DIAG enable","DIAG disable","ROOT magisk patch boot","FLASH magisk patched boot","FLASH TWRP recovery","DUMP preloader via brom","BROM bypass auth","READ chip info HWID+OEM PK hash","LIVE protocol console"])

open("app/src/main/java/com/otgflasher/pro/MainActivity.java","w").write('package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.content.Intent;public class MainActivity extends Activity{@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);findViewById(R.id.cFastboot).setOnClickListener(v->startActivity(new Intent(this, FastbootActivity.class)));findViewById(R.id.cMtk).setOnClickListener(v->startActivity(new Intent(this, MtkActivity.class)));findViewById(R.id.cEdl).setOnClickListener(v->startActivity(new Intent(this, EdlActivity.class)));findViewById(R.id.cOdin).setOnClickListener(v->startActivity(new Intent(this, OdinActivity.class)));findViewById(R.id.cSpd).setOnClickListener(v->startActivity(new Intent(this, SpdActivity.class)));findViewById(R.id.cPayload).setOnClickListener(v->startActivity(new Intent(this, PayloadActivity.class)));findViewById(R.id.cSuper).setOnClickListener(v->startActivity(new Intent(this, SuperActivity.class)));findViewById(R.id.cOfp).setOnClickListener(v->startActivity(new Intent(this, OfpActivity.class)));findViewById(R.id.cFrp).setOnClickListener(v->startActivity(new Intent(this, FrpActivity.class)));findViewById(R.id.cMi).setOnClickListener(v->startActivity(new Intent(this, MiActivity.class)));findViewById(R.id.cQcn).setOnClickListener(v->startActivity(new Intent(this, QcnActivity.class)));findViewById(R.id.cKg).setOnClickListener(v->startActivity(new Intent(this, KgActivity.class)));findViewById(R.id.cUnlock).setOnClickListener(v->startActivity(new Intent(this, UnlockActivity.class)));findViewById(R.id.cPart).setOnClickListener(v->startActivity(new Intent(this, PartActivity.class)));findViewById(R.id.cAdb).setOnClickListener(v->startActivity(new Intent(this, AdbActivity.class)));findViewById(R.id.cSahara).setOnClickListener(v->startActivity(new Intent(this, SaharaActivity.class)));}}')

jt='''package com.otgflasher.pro;import android.app.Activity;import android.os.Bundle;import android.widget.*;import java.io.*;public class CLASS extends Activity{TextView txtDetail,log;ProgressBar bar;@Override protected void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.LAY);txtDetail=findViewById(R.id.txtDetail);log=findViewById(R.id.logView);bar=findViewById(R.id.progressBar);findViewById(R.id.btnBack).setOnClickListener(v->finish());CMDS}void run(String c){bar.setProgress(5);log.append("\\n> "+c+"\\n");new Thread(()->{try{Process p=Runtime.getRuntime().exec(new String[]{"sh","-c",c+" 2>&1"});BufferedReader r=new BufferedReader(new InputStreamReader(p.getInputStream()));String l;int pr=5;while((l=r.readLine())!=null){pr+=2;if(pr>95)pr=95;String ll=l;int pp=pr;runOnUiThread(()->{bar.setProgress(pp);txtDetail.setText(pp+"% "+ll);log.append(ll+"\\n");});}p.waitFor();runOnUiThread(()->bar.setProgress(100));}catch(Exception e){runOnUiThread(()->log.append("ERR "+e.getMessage()+"\\n"));}}).start();}}'''
def j(cls,lay,cmds):
    code=""
    for txt,shell in cmds:
        safe=txt.replace(" ","_").replace("/","_").replace("+","_")
        code+=f'findViewById(R.id.btn_{safe}).setOnClickListener(v->run("{shell}"));\n'
    content=jt.replace("CLASS",cls).replace("LAY",lay).replace("CMDS",code)
    open(f"app/src/main/java/com/otgflasher/pro/{cls}.java","w").write(content)

j("FastbootActivity","activity_fastboot",[("FLASH boot_a","fastboot flash boot_a /sdcard/Download/boot.img"),("FLASH boot_b","fastboot flash boot_b /sdcard/Download/boot.img"),("FLASH boot","fastboot flash boot /sdcard/Download/boot.img"),("FLASH recovery","fastboot flash recovery /sdcard/Download/recovery.img"),("FLASH vbmeta","fastboot flash vbmeta /sdcard/Download/vbmeta.img --disable-verity --disable-verification"),("FLASH vbmeta_a","fastboot flash vbmeta_a /sdcard/Download/vbmeta.img --disable-verity --disable-verification"),("FLASH vbmeta_b","fastboot flash vbmeta_b /sdcard/Download/vbmeta.img"),("FLASH super","fastboot flash super /sdcard/Download/super.img"),("FLASH system","fastboot flash system /sdcard/Download/system.img"),("FLASH vendor","fastboot flash vendor /sdcard/Download/vendor.img"),("FLASH dtbo","fastboot flash dtbo /sdcard/Download/dtbo.img"),("FLASH modem","fastboot flash modem /sdcard/Download/modem.img"),("ERASE frp","fastboot erase frp"),("ERASE userdata","fastboot erase userdata"),("ERASE cache","fastboot erase cache"),("GETVAR all","fastboot getvar all"),("GETVAR unlocked","fastboot getvar unlocked"),("OEM device-info","fastboot oem device-info"),("FLASHING unlock","fastboot flashing unlock"),("FLASHING lock","fastboot flashing lock"),("OEM unlock-go","fastboot oem unlock-go"),("REBOOT bootloader","fastboot reboot bootloader"),("REBOOT recovery","fastboot reboot recovery"),("REBOOT edl","fastboot reboot edl"),("REBOOT system","fastboot reboot")])
j("MtkActivity","activity_mtk",[("BYPASS AUTH SLA DAA","python3 -m mtk payload"),("DOWNLOAD ONLY","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt"),("FIRMWARE UPGRADE","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --firmware-upgrade"),("FORMAT ALL + DOWNLOAD","python3 -m mtk w --scatter /sdcard/Download/MT6765_scatter.txt --format-all"),("READBACK ADD","python3 -m mtk r --help"),("READBACK boot 0x0 0x2000000","python3 -m mtk r boot /sdcard/Download/boot.img"),("READBACK preloader","python3 -m mtk r preloader /sdcard/Download/preloader.bin"),("READBACK nvram","python3 -m mtk r nvram /sdcard/Download/nvram.img"),("FORMAT Auto Format","python3 -m mtk e frp,userdata,cache"),("FORMAT Manual Format frp 0x0 0x100000","python3 -m mtk e frp"),("FORMAT whole flash except bootloader","python3 -m mtk e frp,userdata,cache,nvram"),("MEMORY TEST RAM","python3 -m mtk da test"),("MEMORY TEST EMMC","python3 -m mtk da test --emmc"),("ERASE FRP","python3 -m mtk e frp"),("ERASE FRP+userdata","python3 -m mtk e frp,userdata"),("STOP","pkill -9 python3")])
j("EdlActivity","activity_edl",[("SAHARA TEST","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara"),("SAHARA Upload","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"),("PRINT GPT UFS","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"),("PRINT GPT EMMC","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=emmc --printgpt"),("PARTITION MANAGER","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt"),("FLASH Flat Build rawprogram+patch","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --rawprogram=/sdcard/Download/rawprogram0.xml --patch=/sdcard/Download/patch0.xml --memory=ufs"),("READ frp 100MB","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=frp --filename=/sdcard/Download/frp.img"),("READ userdata 1GB","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --r --memoryname=userdata --filename=/sdcard/Download/userdata.img"),("ERASE frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"),("ERASE userdata","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=userdata"),("BACKUP QCN modemst1+modemst2+fsg","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img; dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img; dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img"),("RESTORE QCN","dd if=/sdcard/Download/modemst1.img of=/dev/block/bootdevice/by-name/modemst1"),("RESET to normal","edl reset"),("SELECT PORT COM","edl --help")])
j("OdinActivity","activity_odin",[("FLASH AP only","heimdall flash --AP /sdcard/Download/AP.tar.md5"),("FLASH BL only","heimdall flash --BL /sdcard/Download/BL.tar.md5"),("FLASH CP only","heimdall flash --CP /sdcard/Download/CP.tar.md5"),("FLASH CSC only","heimdall flash --CSC /sdcard/Download/CSC.tar.md5"),("FLASH HOME_CSC","heimdall flash --CSC /sdcard/Download/HOME_CSC.tar.md5"),("FLASH FULL AP+BL+CP+CSC","heimdall flash --AP /sdcard/Download/AP.tar.md5 --BL /sdcard/Download/BL.tar.md5 --CP /sdcard/Download/CP.tar.md5 --CSC /sdcard/Download/CSC.tar.md5"),("READ PIT","heimdall print-pit"),("WRITE PIT","heimdall flash --pit /sdcard/Download/pit.pit"),("DUMP PIT","heimdall download-pit --output /sdcard/Download/pit.pit"),("BYPASS KG","adb shell pm disable-user --user 0 com.samsung.android.kgclient"),("BYPASS MDM","adb shell pm disable-user --user 0 com.samsung.android.mdm"),("BYPASS FRP","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"),("ERASE Nand All","heimdall flash --no-reboot --resume -- Pit + --Nand Erase All"),("REBOOT Download","adb reboot download"),("REBOOT System","adb reboot")])
j("SpdActivity","activity_spd",[("FLASH PAC","python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac"),("FLASH PAC Format All","python3 /sdcard/Download/spd_flash.py --pac /sdcard/Download/firmware.pac --format-all"),("READ INFO","python3 /sdcard/Download/spd_info.py"),("READ FLASH","python3 /sdcard/Download/spd_read.py"),("FORMAT","python3 /sdcard/Download/spd_format.py"),("BYPASS FRP","python3 /sdcard/Download/spd_frp.py"),("DIAG MODE","python3 /sdcard/Download/spd_diag.py"),("BACKUP PAC","python3 /sdcard/Download/spd_backup.py")])
j("PayloadActivity","activity_payload",[("LIST partitions","python3 -m payload_dumper --list /sdcard/Download/payload.bin"),("EXTRACT ALL","python3 -m payload_dumper /sdcard/Download/payload.bin --out /sdcard/Download/out/"),("EXTRACT boot","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions boot --out /sdcard/Download/out/"),("EXTRACT system","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions system --out /sdcard/Download/out/"),("EXTRACT vendor","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions vendor --out /sdcard/Download/out/"),("EXTRACT product","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions product --out /sdcard/Download/out/"),("EXTRACT super","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions super --out /sdcard/Download/out/"),("EXTRACT dtbo","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions dtbo --out /sdcard/Download/out/"),("EXTRACT vbmeta","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions vbmeta --out /sdcard/Download/out/"),("EXTRACT odm","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions odm --out /sdcard/Download/out/"),("EXTRACT system_ext","python3 -m payload_dumper /sdcard/Download/payload.bin --partitions system_ext --out /sdcard/Download/out/")])
j("SuperActivity","activity_super",[("LPDUMP list inside super","lpdump /sdcard/Download/super.img"),("LPUNPACK all","lpunpack /sdcard/Download/super.img /sdcard/Download/out/"),("EXTRACT system","cp /sdcard/Download/out/system.img /sdcard/Download/system.img"),("EXTRACT vendor","cp /sdcard/Download/out/vendor.img /sdcard/Download/vendor.img"),("EXTRACT product","cp /sdcard/Download/out/product.img /sdcard/Download/product.img"),("EXTRACT system_ext","cp /sdcard/Download/out/system_ext.img /sdcard/Download/system_ext.img"),("EXTRACT odm","cp /sdcard/Download/out/odm.img /sdcard/Download/odm.img"),("MOUNT system","mkdir -p /mnt/system; mount -o loop /sdcard/Download/out/system.img /mnt/system"),("RESIZE super","lpresize /sdcard/Download/super.img 0"),("LPMAKE new super","lpmake --help"),("FLASH super fastboot","fastboot flash super /sdcard/Download/super.img")])
j("OfpActivity","activity_ofp",[("EXTRACT OFP all","python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/"),("EXTRACT super only","python3 /sdcard/Download/ofp_extractor.py /sdcard/Download/firmware.ofp /sdcard/Download/out/ --only super"),("DECRYPT OFP","python3 /sdcard/Download/ofp_decrypt.py /sdcard/Download/firmware.ofp"),("LIST OFP files","python3 /sdcard/Download/ofp_extractor.py --list /sdcard/Download/firmware.ofp"),("FLASH OFP extracted","fastboot flash super /sdcard/Download/out/super.img"),("CONVERT OFP to scatter","python3 /sdcard/Download/ofp_to_scatter.py /sdcard/Download/firmware.ofp")])
j("FrpActivity","activity_frp",[("ADB settings user_setup_complete 1","adb shell content insert --uri content://settings/secure --bind name:s:user_setup_complete --bind value:s:1"),("ADB rm accounts.db","adb shell rm /data/system/users/0/accounts.db; adb shell rm /data/system/users/0/accounts_ce.db"),("ADB pm clear gsf login+gms","adb shell pm clear com.google.android.gsf.login; adb shell pm clear com.google.android.gms"),("FASTBOOT erase frp","fastboot erase frp"),("FASTBOOT erase config","fastboot erase config"),("FASTBOOT erase persist","fastboot erase persist"),("FASTBOOT erase frp+config+persist","fastboot erase frp; fastboot erase config; fastboot erase persist"),("MTK erase frp+nvram+nvdata","python3 -m mtk e frp,nvram,nvdata"),("EDL erase frp","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --erase --memoryname=frp"),("SAMSUNG Talkback bypass","adb shell am start -n com.google.android.gsf.login/com.google.android.gsf.login.LoginActivity"),("SAMSUNG YouTube bypass","adb shell am start -a android.intent.action.VIEW -d https://www.google.com"),("UNIVERSAL FRP am start google","adb shell am start -a android.intent.action.VIEW -d https://www.google.com"),("RESET FRP","fastboot erase frp; fastboot erase config")])
j("MiActivity","activity_mi",[("DISABLE FindDevice pm disable","adb shell pm disable-user --user 0 com.xiaomi.finddevice"),("ERASE micloud data","adb shell rm -rf /data/system/micloud; adb shell rm -rf /data/system/users/0/micloud"),("DISABLE micloud settings","adb shell settings put secure micloud_status 0; adb shell settings put secure find_device_enabled 0"),("ERASE frp","fastboot erase frp"),("ERASE persist","fastboot erase persist"),("BYPASS Mi Account xmsf+micloudsdk","adb shell pm disable-user --user 0 com.xiaomi.xmsf; adb shell pm disable-user --user 0 com.xiaomi.micloudsdk"),("FLASH persist.img","fastboot flash persist /sdcard/Download/persist.img"),("REMOVE Mi Account persist","fastboot erase persist; fastboot flash persist /sdcard/Download/persist.img"),("REBOOT","adb reboot")])
j("QcnActivity","activity_qcn",[("BACKUP modemst1 dd","dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/modemst1.img bs=4096"),("BACKUP modemst2 dd","dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/modemst2.img bs=4096"),("BACKUP fsg dd","dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/fsg.img bs=4096"),("BACKUP fsc dd","dd if=/dev/block/bootdevice/by-name/fsc of=/sdcard/Download/fsc.img bs=4096"),("BACKUP efs1+efs2 dd","dd if=/dev/block/bootdevice/by-name/efs1 of=/sdcard/Download/efs1.img; dd if=/dev/block/bootdevice/by-name/efs2 of=/sdcard/Download/efs2.img"),("BACKUP FULL 4 files","mkdir -p /sdcard/Download/qcn_full; dd if=/dev/block/bootdevice/by-name/modemst1 of=/sdcard/Download/qcn_full/modemst1.img; dd if=/dev/block/bootdevice/by-name/modemst2 of=/sdcard/Download/qcn_full/modemst2.img; dd if=/dev/block/bootdevice/by-name/fsg of=/sdcard/Download/qcn_full/fsg.img; dd if=/dev/block/bootdevice/by-name/fsc of=/sdcard/Download/qcn_full/fsc.img"),("RESTORE modemst1","dd if=/sdcard/Download/modemst1.img of=/dev/block/bootdevice/by-name/modemst1 bs=4096"),("RESTORE modemst2","dd if=/sdcard/Download/modemst2.img of=/dev/block/bootdevice/by-name/modemst2 bs=4096"),("RESTORE fsg","dd if=/sdcard/Download/fsg.img of=/dev/block/bootdevice/by-name/fsg bs=4096"),("RESTORE efs1+efs2","dd if=/sdcard/Download/efs1.img of=/dev/block/bootdevice/by-name/efs1; dd if=/sdcard/Download/efs2.img of=/dev/block/bootdevice/by-name/efs2"),("DIAG enable diag,adb","adb shell setprop sys.usb.config diag,adb; adb shell setprop persist.usb.config diag,adb"),("QCN Rebuild","echo qcn rebuild via qpst")])
j("KgActivity","activity_kg",[("DISABLE KGCLIENT","adb shell pm disable-user --user 0 com.samsung.android.kgclient"),("DISABLE MDM service","adb shell pm disable-user --user 0 com.samsung.android.mdm; adb shell pm disable-user --user 0 com.samsung.android.mdm.service"),("DISABLE KNOX kpecore+securefolder","adb shell pm disable-user --user 0 com.samsung.knox.kpecore; adb shell pm disable-user --user 0 com.samsung.knox.securefolder"),("UNINSTALL KGCLIENT","adb shell pm uninstall -k --user 0 com.samsung.android.kgclient"),("UNINSTALL MDM","adb shell pm uninstall -k --user 0 com.samsung.android.mdm"),("BYPASS settings kg_state 0","adb shell settings put secure kg_state 0; adb shell settings put secure kg_locked 0"),("BYPASS build.prop ro.config.knox 0","adb shell setprop ro.config.knox 0; adb shell setprop ro.config.kg 0"),("SAMFW Tool FRP start","adb shell am start -n com.samfw.frp/com.samfw.frp.MainActivity"),("CLEAR KGCLIENT+reboot","adb shell pm clear com.samsung.android.kgclient; adb reboot"),("RESET KG","adb shell pm clear com.samsung.android.kgclient; adb reboot")])
j("UnlockActivity","activity_unlock",[("CHECK device-info+getvar unlocked+get_unlock_ability","fastboot oem device-info; fastboot getvar unlocked; fastboot flashing get_unlock_ability"),("FLASHING unlock","fastboot flashing unlock"),("FLASHING unlock_critical","fastboot flashing unlock_critical"),("OEM unlock","fastboot oem unlock"),("OEM unlock-go","fastboot oem unlock-go"),("FLASHING lock","fastboot flashing lock"),("FLASHING lock_critical","fastboot flashing lock_critical"),("OEM lock","fastboot oem lock"),("MTK seccfg unlock","python3 -m mtk da seccfg unlock"),("MTK xflash seccfg unlock","python3 -m mtk xflash seccfg unlock"),("SAMSUNG OEM unlock","adb shell svc oem unlock; fastboot oem unlock"),("RELOCK","fastboot flashing lock; fastboot oem lock")])
j("PartActivity","activity_part",[("PRINT sgdisk sda+sdb","sgdisk --print /dev/block/sda; sgdisk --print /dev/block/sdb"),("PRINT gdisk -l sda","gdisk -l /dev/block/sda"),("PRINT parted sda print","parted /dev/block/sda print"),("LIST by-name","ls -l /dev/block/bootdevice/by-name/"),("BACKUP GPT 34 sectors","dd if=/dev/block/sda of=/sdcard/Download/gpt_backup.img bs=512 count=34"),("RESTORE GPT","dd if=/sdcard/Download/gpt_backup.img of=/dev/block/sda bs=512 count=34"),("BACKUP all partitions list","ls -l /dev/block/bootdevice/by-name/ > /sdcard/Download/part_list.txt; cat /sdcard/Download/part_list.txt"),("ERASE frp","fastboot erase frp; sgdisk --delete 1 /dev/block/sda"),("ERASE userdata","fastboot erase userdata"),("RESIZE super lpresize 0","lpresize /dev/block/super 0; lpresize /sdcard/Download/super.img 0"),("CREATE partition","sgdisk --new=1:0:0 --typecode=1:8300 /dev/block/sda"),("DELETE partition","sgdisk --delete 1 /dev/block/sda"),("BACKUP super","dd if=/dev/block/super of=/sdcard/Download/super_backup.img bs=4096"),("FLASH super","fastboot flash super /sdcard/Download/super_backup.img")])
j("AdbActivity","activity_adb",[("DEVICES adb devices","adb devices"),("SHELL adb shell","adb shell"),("LOGCAT adb logcat","adb logcat"),("INSTALL APK","adb install /sdcard/Download/app.apk"),("PUSH file to sdcard","adb push /sdcard/Download/file.txt /sdcard/Download/"),("PULL file from sdcard","adb pull /sdcard/Download/file.txt /sdcard/Download/pull/"),("SCREENCAP","adb shell screencap /sdcard/Download/screen.png"),("SCREENRECORD","adb shell screenrecord /sdcard/Download/record.mp4"),("REBOOT","adb reboot"),("REBOOT bootloader","adb reboot bootloader"),("REBOOT recovery","adb reboot recovery"),("REBOOT edl","adb reboot edl"),("ROOT adb root","adb root"),("REMOUNT","adb remount"),("DISABLE-VERITY","adb disable-verity"),("SHELL pm list packages","adb shell pm list packages")])
j("SaharaActivity","activity_sahara",[("SAHARA TEST chip id","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara --print-chip-id"),("SAHARA Upload loader","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --sahara"),("DIAG enable","adb shell setprop sys.usb.config diag,adb"),("DIAG disable","adb shell setprop sys.usb.config mtp,adb"),("ROOT magisk patch boot","python3 /sdcard/Download/magisk_patch.py /sdcard/Download/boot.img"),("FLASH magisk patched boot","fastboot flash boot /sdcard/Download/magisk_patched.img"),("FLASH TWRP recovery","fastboot flash recovery /sdcard/Download/twrp.img"),("DUMP preloader via brom","python3 -m mtk r preloader /sdcard/Download/preloader_dump.bin"),("BROM bypass auth","python3 -m mtk payload"),("READ chip info HWID+OEM PK hash","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --sahara --print-chip-id"),("LIVE protocol console","edl --loader=/sdcard/Download/prog_firehose_ddr.elf --memory=ufs --printgpt --verbose")])

print("v22 PC PARITY 16 TOOLS DONE")
