plugins {
    id 'com.android.application'
}
android {
    namespace 'com.otgflasher.pro'
    compileSdk 34
    defaultConfig {
        applicationId "com.otgflasher.pro"
        minSdk 24
        targetSdk 34
        versionCode 26
        versionName "26.0-REAL-TERMUX"
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies {
}
